---
settings:
  name: Astra Control Center
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "release-notes/whats-new.html"
  versions:
    - name: Astra Control Center
      url: /astra-control-center
      version-number: "23.07"
    - name: Astra Control Center
      url: /astra-control-center-2304
      version-number: "23.04"
    - name: Astra Control Center
      url: /astra-control-center-2211
      version-number: "22.11"
    - name: Astra Control Center
      url: /astra-control-center-2208
      version-number: "22.08"
    - name: Astra Control Center
      url: /astra-control-center-2204
      version-number: "22.04"
    - name: Astra Control Center
      url: /astra-control-center-2112
      version-number: "21.12"
sidebar:
  entries:
    - title: Astra Control Center docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: concepts
    - section: use
    - section: use-acp
    - section: rest-api
    #- section: solutions (retired with DOC-4309)
    - section: support
    - title: Earlier versions
      url: /acc-earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: All Astra documentation

