---
settings:
  name: Astra Control Center
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "release-notes/whats-new.html"
  versions:
    - name: Astra Control Center
      url: /astra-control-center
      version-number: "22.11"
    - name: Astra Control Center
      url: /astra-control-center-2208
      version-number: "22.08"
    - name: Astra Control Center
      url: /astra-control-center-2204
      version-number: "22.04"
    - name: Astra Control Center
      url: /astra-control-center-2112
      version-number: "21.12"
sidebar:
  entries:
    - title: Astra Control Center docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: concepts
    - section: use
    - section: rest-api
    #- section: solutions (retired with DOC-4309)
    - section: support
    - title: Earlier versions
      url: /acc-earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: All Astra documentation

homepage:
  tiles:
    - title: Get started with Astra Control Center
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Control Center
          url: /get-started/intro.html
        - title: What's new in Astra Control Center
          url: /release-notes/whats-new.html
        - title: Release notes
          url: /release-notes/rn_overview.html
        - title: Try it out
          url: /get-started/quick-start.html
        - title: Install Astra Control Center
          url: /get-started/install_acc.html
    - title: Use Astra Control Center
      links:
        - title: Manage accounts
          url: /use/manage-local-users-and-roles.html
        - title: Manage apps
          url: /use/manage-apps.html
        - title: Protect apps
          url: /use/protect-apps.html
        - title: Clone and migrate apps
          url: /use/clone-apps.html
        - title: Replicate apps to a remote system
          url: /use/replicate_snapmirror.html
    - title: Use Astra Control REST API
      links:
        - title: Get started with the Astra Control API
          url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
        - title: API reference
          url: https://docs.netapp.com/us-en/astra-automation/reference/overview.html
        - title: API workflows
          url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
#    - title: Use Astra Control Center in VMware
#      links:
#        - title: Get started in VMware
#        - title: Manage apps using VMware
#        - title: Protect apps using VMware
#        - title: Migrate apps using VMware
    - title: Use Astra Control Service
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Control Service
          url: https://docs.netapp.com/us-en/astra/get-started/intro.html
        - title: What's new in Astra Control Service
          url: https://docs.netapp.com/us-en/astra/release-notes/whats-new.html
        - title: Quick start for Astra Control Service
          url: https://docs.netapp.com/us-en/astra/get-started/quick-start.html
#    - title: Use Astra Service
#      links:
#        - title: Manage accounts
#          url: https://docs.netapp.com/us-en/astra/use/manage-users.html
#        - title: Manage apps
#          url: https://docs.netapp.com/us-en/astra/use/manage-apps.html
#        - title: Protect apps
#          url: https://docs.netapp.com/us-en/astra/use/protect-apps.html
#        - title: Migrate apps
#          url: https://docs.netapp.com/us-en/astra/use/clone-apps.html
#        - title: Set up billing
#          url: https://docs.netapp.com/us-en/astra/use/set-up-billing.html
    - title: Solution briefs
      links:
        - title: PostgreSQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
        - title: MySQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
        - title: Simplify Jenkins lifecycle management
          url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
    - title: Blogs & community
      links:
        - title: Discord channel
          url: https://discord.gg/NetApp
        - title: Astra Control blog
          url: https://cloud.netapp.com/blog/topic/astra
        - title: NetApp Community
          url: https://community.netapp.com/
        - title: Kubernetes Hub
          url: https://cloud.netapp.com/kubernetes-hub
        - title: Where to get help
          url: /support/get-help.html
