---
sidebar: sidebar
permalink: learn/choose-class-and-size.html
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance
summary: Astra uses Cloud Volumes Service for Google Cloud as the backend storage for persistent volumes. You should understand how choosing a service level, storage class, and persistent volume size can help you meet your performance objectives.
---

= Choosing a service type, storage class, and PV size
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
Astra Enterprise uses Trident with ONTAP as the backend storage for persistent volumes. You should understand how choosing a service type, storage class, and persistent volume size can help you meet your performance objectives.

== Overview

*??? REDO all for Astra Enterprise*

Astra Enterprise discovers and uses the already-deployed resources, including ONTAP, Trident, and associated storage classes.

=== Storage classes

Three service levels are supported: Standard, Premium, and Extreme. When you add compute to Astra, you're prompted to choose either Standard, Premium, or Extreme as the default storage class for persistent volumes. Each of these service levels are designed for different capacity and bandwidth needs.



=== Persistent volume size and performance

The allowed bandwidth for each service level is per GiB of provisioned capacity. That means larger volumes will provide better performance.

??? See Trident information that provides cost comparisons and examples that can help you better understand how to couple a service level with volume size to meet your performance objectives.

=== Minimum volume size

Astra provisions persistent volumes using a minimum volume size of 100 GiB with the minimum service type, even if the PVC asks for a smaller volume size. For example, if the PVC in a Helm chart asks for 6 GiB, Astra automatically provisions a 100 GiB volume.
