== Add the images to your local registry

. Complete the appropriate step sequence for your container engine:

// start tabbed block for docker and podman approaches

[role="tabbed-block"]
====

.Docker
--
.. Change to the root directory of the tarball. You should see this file and directory:
+
`acc.manifest.bundle.yaml`
`acc/`

.. Push the package images in the Astra Control Center image directory to your local registry. Make the following substitutions before running the `push-images` command:
+

* Replace <BUNDLE_FILE> with the name of the Astra Control bundle file (`acc.manifest.bundle.yaml`).
* Replace <MY_FULL_REGISTRY_PATH> with the URL of the Docker repository; for example, "https://<docker-registry>".
* Replace <MY_REGISTRY_USER> with the user name.
* Replace <MY_REGISTRY_TOKEN> with an authorized token for the registry.
+
[source,console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----
--

.Podman
--
.. Change to the root directory of the tarball. You should see this file and directory:
+
`acc.manifest.bundle.yaml`
`acc/`

.. Log in to your registry:
+
[source,console]
----
podman login <YOUR_REGISTRY>
----

.. Prepare and run one of the following scripts that is customized for the version of Podman you use. Substitute <MY_FULL_REGISTRY_PATH> with the URL of your repository that includes any sub-directories.
+
[source]
[subs="specialcharacters,quotes"]
----
*Podman 4*
----
+
[source,console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=23.04.2-7
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do 
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImageNoPath} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----
+
[source]
[subs="specialcharacters,quotes"]
----
*Podman 3*
----
+
[source,console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=23.04.2-7
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do 
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImageNoPath} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----

+
NOTE: The image path the script creates should resemble the following, depending on your registry configuration: 
+
----
https://netappdownloads.jfrog.io/docker-astra-control-prod/netapp/astra/acc/23.04.2-7/image:version
----

====

// end tabbed block