[role="tabbed-block"]
====

.Astra Trident operator
--

. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html#step-1-download-the-trident-installer-package[Download the Astra Trident installer and extract it^].

. Complete these steps if you have not yet installed Astra Trident or if you removed the operator from your original Astra Trident deployment:

.. Create the CRD:
+
[source,console]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----

.. Create the trident namespace (`kubectl create namespace trident`) or confirm that the trident namespace still exists (`kubectl get all -n trident`). If the namespace has been removed, create it again.

. Update Astra Trident to 24.02.0:
+
NOTE: For clusters running Kubernetes 1.24 or earlier, use `bundle_pre_1_25.yaml`. For clusters running Kubernetes 1.25 or later, use `bundle_post_1_25.yaml`.
+
[source,console]
----
kubectl -n trident apply -f trident-installer/deploy/<bundle-name.yaml>
----

. Verify Astra Trident is running:
+
[source,console]
----
kubectl get torc -n trident
----
+
Response:
+
----
NAME      AGE
trident   21m
----

. [[pull-secrets]]If you have a registry that uses secrets, create a secret to use to pull the Astra Control Provisioner image:
+
[source,console]
----
kubectl create secret docker-registry <secret_name> -n trident --docker-server=<my_custom_registry> --docker-username=<username> --docker-password=<token>
----

. Edit the TridentOrchestrator CR and make the following edits:
+
[source,console]
----
kubectl edit torc trident -n trident
----
+
.. Set a custom registry location for the Astra Trident image or pull it from the Astra Control registry (`tridentImage: <my_custom_registry>/trident:24.02.0` or `tridentImage: netapp/trident:24.02.0`).
.. Enable Astra Control Provisioner (`enableACP: true`).
.. Set the custom registry location for the Astra Control Provisioner image or pull it from the Astra Control registry (`acpImage: <my_custom_registry>/trident-acp:24.02.0` or `acpImage: cr.astra.netapp.io/astra/trident-acp:24.02.0`).
.. If you established <<pull-secrets,image pull secrets>> earlier in this procedure, you can set them here (`imagePullSecrets: - <secret_name>`). Use the same name secret name you established in the previous steps.

+
[subs=+quotes]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  *tridentImage: <registry>/trident:24.02.0*
  *enableACP: true*
  *acpImage: <registry>/trident-acp:24.02.0*
  *imagePullSecrets:
  - <secret_name>*
----

. Save and exit the file. The deployment process will begin automatically.

. Verify the operator, deployment, and replicasets are created.
+
[source,console]
----
kubectl get all -n trident
----
+
IMPORTANT: There should only be *one instance* of the operator in a Kubernetes cluster. Do not create multiple deployments of the Astra Trident operator.

. Verify the `trident-acp` container is running and that `acpVersion` is `24.02.0` with a status of `Installed`:
+
[source,console]
----
kubectl get torc -o yaml
----
+
Response:
+
----
status:
  acpVersion: 24.02.0
  currentInstallationParams:
    ...
    acpImage: <registry>/trident-acp:24.02.0
    enableACP: "true"
    ...
  ...
  status: Installed
----
--

.tridentctl
--

. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-tridentctl.html#step-1-download-the-trident-installer-package[Download the Astra Trident installer and extract it^].
. https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-tridentctl.html[If you have an existing Astra Trident, uninstall it from the cluster that hosts it^].
. Install Astra Trident with Astra Control Provisioner enabled (`--enable-acp=true`):
+
[source,console]
----
./tridentctl -n trident install --enable-acp=true --acp-image=mycustomregistry/trident-acp:24.02
----

. Confirm that Astra Control Provisioner has been enabled:
+
[source,console]
----
./tridentctl -n trident version
----
+
Response:
+
----
+----------------+----------------+-------------+ | SERVER VERSION | CLIENT VERSION | ACP VERSION | +----------------+----------------+-------------+ | 24.02.0 | 24.02.0 | 24.02.0. | +----------------+----------------+-------------+
----
--

.Helm
--

. If you have Astra Trident 23.07.1 or earlier installed, https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html#uninstall-a-trident-operator-installation[uninstall^] the operator and other components.

. If your Kubernetes cluster is running 1.24 or earlier, delete psp: 
+
----
kubectl delete psp tridentoperatorpod
----

. Add the Astra Trident Helm repository:
+
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----

. Update the Helm chart:
+
----
helm repo update netapp-trident
----
+
Response:
+
----
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "netapp-trident" chart repository
Update Complete. ⎈Happy Helming!⎈
----

. List the images:
+
----
./tridentctl images -n trident
----
+
Response:
+
----
| v1.28.0            | netapp/trident:24.02.0|
|                    | docker.io/netapp/trident-autosupport:24.02|
|                    | registry.k8s.io/sig-storage/csi-provisioner:v4.0.0|
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.5.0|
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.9.3|
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3|
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0 |
|                    | netapp/trident-operator:24.02.0 (optional)
----

. Ensure that trident-operator 24.02.0 is available:
+
----
helm search repo netapp-trident/trident-operator --versions
----
+
Response:
+
----
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
netapp-trident/trident-operator 100.2402.0      24.02.0         A
----

. Use `helm install` and run one of the following options that include these settings: 
+
** A name for your deployment location
** The Astra Trident version
** The name of the Astra Control Provisioner image
** The flag to enable the provisioner
** (Optional) A local registry path. If you are using a local registry, your https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions[Trident images^] can be located in one registry or different registries, but all CSI images must be located in the same registry.
** The Trident namespace

.Options

* Images without a registry
+
//----
//helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<acp image> --set enableACP=true --create-namespace --namespace trident
//----
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=cr.astra.netapp.io/astra/trident-acp:24.02.0 --set enableACP=true --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----

* Images in one or more registries
+
//----
//helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --create-namespace --namespace trident
//----
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<your-registry>:<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----
//
//* Images in different registries
//+
//----
//helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --set operatorImage=<your-registry>/netapp/trident-operator:24.02.0 --set tridentAutosupportImage=<your-registry>/netapp/trident-autosupport:24.02 --set tridentImage=<your-registry>/netapp/trident:24.02.0 --create-namespace --namespace trident
//----
//----
//helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<your-registry>:<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
//----

You can use `helm list` to review installation details such as name, namespace, chart, status, app version, and revision number.

[NOTE]
=====
If you have any issues deploying Trident using Helm, run this command to fully uninstall Astra Trident:

----
./tridentctl uninstall -n trident
----

*Do not* https://docs.netapp.com/us-en/trident/troubleshooting.html#completely-remove-astra-trident-and-crds[completely remove Astra Trident CRDs^] as part of your uninstall before attempting to enable Astra Control Provisioner again.
=====

--
====
// end tabbed block