---
sidebar: sidebar
permalink: use-acp/configure-storage-backend-encryption.html
keywords: astra control center, acp, astra control provisioner, backend, storage, encryption, kerberos
summary: You can configure encryption to protect the traffic between Astra Control and your storage backend.
---

= Configure storage backend encryption
:hardbreaks:
:icons: font
:imagesdir: ../media/use-acp/

[.lead]
Using Astra Control Provisioner, you can improve storage security by enabling encryption for the traffic between your managed cluster and the storage backend. 

Astra Control Provisioner supports Kerberos 5 encryption over NFSv4.1 connections from Red Hat OpenShift clusters to Azure NetApp Files volumes.

== Configure Kerberos encryption with Azure NetApp Files volumes
You can enable Kerberos encryption on the storage traffic between your managed cluster and a single Azure NetApp Files storage backend or a virtual pool of Azure NetApp Files storage backends. 

.Before you begin

* Ensure that you have installed the latest version of Astra Control Provisioner on the managed Red Hat OpenShift cluster.
* Ensure that your environment meets the requirements in the https://learn.microsoft.com/en-us/azure/azure-netapp-files/configure-kerberos-encryption#requirements[Azure NetApp Files documentation^].
* Ensure that you have prepared the Azure NetApp Files storage backend for Kerberos encryption by following the instructions in https://learn.microsoft.com/en-us/azure/azure-netapp-files/configure-kerberos-encryption[Azure NetApp Files documentation^].

.About this task
You can create a configuration file that should be applied at the storage backend level, using the `kerberos` key, or at the virtual pool level, using the `storage` key. When you define the configuration at the virtual pool level, the pool is selected using the label in the storage class.

.Steps

. On the managed cluster, create a storage backend configuration file. Replace values in brackets <> with information from your environment:
+
[role="tabbed-block"]
====

.Storage backend level
--
[source,yaml]
----
version: 1
storageDriverName: azure-netapp-files
subscriptionID: <SUBSCRIPTION_ID>
tenantID: <TENANT_ID>
clientID: <CLIENT_ID>
clientSecret: <CLIENT_SECRET>
location: <LOCATION>
serviceLevel: Standard
networkFeatures: Standard
capacityPools:
- <CAPACITY_POOL>
resourceGroups:
- <RESOURCE_GROUP>
netappAccounts:
- <NETAPP_ACCOUNT>
virtualNetwork: <VIRTUAL_NETWORK>
subnet: <SUBNET>
nasType: nfs
kerberos: sec=krb5i
----
--

.Virtual pool level
--
[source,yaml]
----
version: 1
storageDriverName: azure-netapp-files
subscriptionID: <SUBSCRIPTION_ID>
tenantID: <TENANT_ID>
clientID: <CLIENT_ID>
clientSecret: <CLIENT_SECRET>
location: <LOCATION>
serviceLevel: Standard
networkFeatures: Standard
capacityPools:
- <CAPACITY_POOL>
resourceGroups:
- <RESOURCE_GROUP>
netappAccounts:
- <NETAPP_ACCOUNT>
virtualNetwork: <VIRTUAL_NETWORK>
subnet: <SUBNET>
nasType: nfs
"storage": [{"labels":{"type”: “encryption"},"kerberos" : "sec=krb5i"}]  
----
--
====

. Perform the next step.






