---
sidebar: sidebar
permalink: concepts/choose-class-and-size.html
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers
summary: Astra Control Center supports various storage backends.  You should understand how storage class and persistent volume size can help you meet your performance objectives.
---

= Storage classes and persistent volume size
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
Astra Control Center supports NetApp ONTAP and Longhorn as storage backends.

== Overview
Astra Control Center supports the following:

* *Storage classes backed by ONTAP storage*: If you are using an ONTAP backend, Astra Control Center offers the ability to import the ONTAP backend to report various monitoring information.
* *CSI-based storage classes backed by Longhorn*: You can use Longhorn with the Longhorn Container Storage Interface (CSI) driver.

NOTE: Storage classes should be https://docs.netapp.com/us-en/trident/trident-use/create-stor-class.html[configured^] using Astra Control Provisioner.

== Storage classes

When you add a cluster to Astra Control Center, you're prompted to select one previously configured storage class on that cluster as the default storage class. This storage class will be used when no storage class is specified in a persistent volume claim (PVC). The default storage class can be changed at any time within Astra Control Center and any storage class can be used at any time by specifying the name of the storage class within the PVC or Helm chart. Ensure that you have only a single default storage class defined for your Kubernetes cluster.