---
sidebar: sidebar
permalink: concepts/choose-class-and-size.html
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers
summary: Astra Control Center supports  Trident storage classes backed by ONTAP storage or Astra Data Store storage classes.  You should understand how storage class and persistent volume size can help you meet your performance objectives.
---

= Storage classes and persistent volume size
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
Astra Control Center supports ONTAP or Astra Data Store as the backend storage. You should understand how storage class and persistent volume (PV) size can help you meet your performance objectives.

== Overview
Astra Control Center supports the following:

* *Astra Data Store storage*: If you installed one or more Astra Data Store clusters manually, Astra Control Center offers the ability to import these and retrieve their topology (nodes, disks) as well as various statuses.

+
Astra Control Center displays the underlying Kubernetes cluster from the Astra Data Store configuration, the cloud that the Kubernetes cluster belongs to, any persistent volumes provisioned by Astra Data Store, the name of the corresponding internal volume, the application using the persistent volume, and the cluster containing the app.
* *Trident storage classes backed by ONTAP storage*:  Astra Control Center discovers and uses the already-deployed resources, including ONTAP, Trident, and associated storage classes.


NOTE: Trident storage classes should be preconfigured outside of Astra Control Center.

== Storage classes

When you add clusters to Astra Control Center, you're prompted to choose one of the previously discovered storage classes for persistent volumes. Service levels in storage classes are designed for different capacity and bandwidth needs. These discovered storage classes are eligible for use within Astra Control Center.

== Persistent volume size and performance

See Trident information that provides cost comparisons and examples that can help you better understand how to couple a service level with volume size to meet your performance objectives.

== Find more information

* https://docs.netapp.com/us-en/trident/index.html[Astra Trident documentation^]
* https://docs.netapp.com/us-en/astra-data-store/index.html[Astra Data Store documentation^]
