---
sidebar: sidebar
permalink: concepts/data-protection.html
keywords: backup, back up, backup apps, back up apps, snapshots, snapshot an app, take a snapshot, take a backup, view backups, view snapshots, set policy, set schedule, schedule backups, schedule snapshots
summary: Learn about the available types of data protection in Astra Control Center, and how best to use them to protect your apps.
---

= Data protection
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

Learn about the available types of data protection in Astra Control Center, and how best to use them to protect your apps.

== Snapshots, backups, and protection policies

A _snapshot_ is a point-in-time copy of an app that's stored on the same provisioned volume as the app. They are usually fast. You can use local snapshots to restore the application to an earlier point in time. Snapshots are useful for fast clones; snapshots include all of the Kubernetes objects for the app, including configuration files.

A _backup_ is stored in the external object store, and can be slower to take compared to local snapshots. You can restore an app backup to the same cluster, or you can migrate an app by restoring its backup to a different cluster. You can also choose a longer retention period for backups. Because they are stored in the external object store, backups generally offer you better protection than snapshots in cases of server failure or data loss.

A _protection policy_ is a way to protect an app by automatically creating snapshots, backups, or both according to a schedule that you define for that app. A protection policy also enables you to choose how many snapshots and backups to retain in the schedule. Automating your backups and snapshots with a protection policy is the best way to ensure each app is protected according to the needs of your organization.

CAUTION: _You can't be fully protected until you have a recent backup_. This is important because backups are stored in an object store away from the persistent volumes. If a failure or accident wipes out the cluster and its associated persistent storage, then you need a backup to recover. A snapshot would not enable you to recover.

== Clones

A _clone_ is an exact duplicate of an app, its configuration, and its persistent storage. You can manually create a clone on either the same Kubernetes cluster or on another cluster. Cloning an app can be useful if you need to move applications and storage from one Kubernetes cluster to another.

== Replication to a remote cluster

Using Astra Control, you can quickly protect applications to a remote cluster in preparation for disaster recovery using SnapMirror technology, a feature of ONTAP.

Astra Control replicates Snapshot backup copies to a remote cluster, providing scheduled, asynchronous, disaster recovery data protection. The replication process can create volume snapshots and app snapshots.

Replicating applications is different than backing up and restoring applications in case of a disaster in the following ways:

* *Replicating applications*: Astra Control uses ONTAP paired clusters that are in a SnapMirror relationship connecting the source Kubernetes cluster and ONTAP system to a destination Kubernetes cluster and ONTAP system. Using SnapMirror, Astra Control replicates Snapshots of applications to a destination ONTAP system. To fail over, Astra Control can quickly bring the replicated application online by recreating the application on the destination Kubernetes cluster with the replicated volumes on the destination ONTAP cluster.
+
Replicating applications places the data on a destination volume and incrementally updates it.

* *Backing up and restoring applications*: When backing up applications, Astra Control creates a Snapshot of the app data and stores it in an object storage bucket. When a restore is needed, the data in the bucket must be copied to a volume on the ONTAP cluster to be accessible, a more lengthy process than replication. The restore process requires this additional copy operation to the destination cluster compared to the replication process, where the application can just start using the replicated data on the destination ONTAP cluster.

To learn how to replicate apps, see link:../use/replication.html[Replicate apps to a remote system using SnapMirror technology].
