---
sidebar: sidebar
permalink: concepts/licensing.html
keywords: license, licensing
summary: Learn about how the actions you can perform with Astra Control Center differ based on license status, and about how your use of Astra Control Center affects license consumption.
---

= Licensing
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
Astra Control Center requires a license to be installed for the full app data management functionality to be enabled. When you deploy Astra Control Center without a license, a banner is displayed in the web UI, warning that system functionality is limited.


//Astra Control Center has full functionality when a license is installed, and reduced functionality without a license. Learn about how the actions you can perform with Astra Control Center differ based on license status, and about how your use of Astra Control Center affects license consumption.

//When no license is installed, the Astra Control Center web UI displays a banner with a message warning that system functionality is limited. In addition to the banner, web UI buttons and API functionality are disabled for the following actions and features:

You need a license to protect your applications and data. Refer to Astra Control Center link:../concepts/intro.html[features] for details.

After you purchase the product, you receive a serial number and license. You can generate the NetApp license file (NLF) from the https://mysupport.netapp.com[NetApp Support Site^]. 

You can also try Astra Control Center with an evaluation license, which lets you use Astra Control Center for 90 days from the date you download the license. For details, refer to link:../get-started/requirements.html[Requirements].

For details about licenses needed for ONTAP storage backends, refer to link:../get-started/requirements.html[supported storage backends].

//The following operations require a valid license:

//* Managing new applications
//* Creating snapshots or backups
//* Configuring a protection policy to schedule snapshots or backups
//* Restoring from a snapshot or backup
//* Cloning from a snapshot or current state
//* Replicating applications to a remote system

//* Applying a new license if the number of CPU cores currently managed by the Astra Control Center instance exceeds the CPU core count in the license being applied

NOTE: You can add a cluster, add a bucket, and manage a storage backend without a license.

//NOTE: On Astra Control Center systems without a license, you can always add a cluster or add a bucket.

== How license consumption is calculated

When you add a new cluster to Astra Control Center, it doesn't count toward consumed licenses until at least one application running on the cluster is managed by Astra Control Center. 


When you start managing an app on a cluster, all of that cluster’s CPU units are included in the Astra Control Center license consumption. 


//However, if all of the managed apps on a cluster are Astra Control Center apps, the cluster is ignored in the consumption calculation. This enables you to use an unlicensed Astra Control Center system to manage another Astra Control Center system and back up and restore its Astra Control Center apps.

//NOTE: You cannot manage Astra Data Store apps in Astra Control Center, but you can use Astra Control Center to manage apps in another Astra Control Center system.

== Find more information
* link:../use/update-licenses.html[Update an existing license]
