---
sidebar: sidebar
permalink: concepts/licensing.html
keywords: license, licensing
summary: Learn about how the actions you can perform with Astra Control Center differ based on license status, and about how your use of Astra Control Center affects license consumption.
---

= Licensing
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
When you deploy Astra Control Center, it is installed with a default evaluation license. If you need more capacity or a longer evaluation period, or want to upgrade to a full license, you can obtain a different evaluation license or full license from NetApp.

You obtain a license in one of the following ways: 

* If you are evaluating Astra Control Center and need different evaluation terms than what is included in the default license, contact NetApp to request a different evaluation license file. An evaluation license lets you use Astra Control Center for 90 days from the date you download the license. 

* link:../concepts/licensing.html[If you already purchased Astra Control Center, generate your NetApp license file (NLF)^] from the NetApp Support Site. After you purchase the product, you receive a serial number and license,  which you use on the Support Site.  

For details about licenses needed for ONTAP storage backends, refer to link:../get-started/requirements.html[supported storage backends].

== How license consumption is calculated

When you add a new cluster to Astra Control Center, it doesn't count toward consumed licenses until at least one application running on the cluster is managed by Astra Control Center.

When you start managing an app on a cluster, all of that cluster's CPU units are included in the Astra Control Center license consumption.

== Find more information
* link:../get-started/setup_overview.html#add-a-license-for-astra-control-center[Add a license when you first set up Astra Control Center]
* link:../use/update-licenses.html[Update an existing license]
