---
sidebar: sidebar
permalink: concepts/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking
summary: Get started by verifying support for your Kubernetes clusters, apps, and web browser.
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

Get started by verifying support for your Kubernetes clusters, apps, licenses, and web browser.

== Kubernetes cluster requirements

A Kubernetes cluster must meet the following requirements so you can discover and manage it from Astra Enterprise.

* *Kubernetes deployment*: Astra Enterprise supports Kubernetes clusters. The cluster should already be deployed in your environment and you should have permissions to manage the existing Kubernetes cluster. This cluster should be preconfigured with the following:
** Load balancer with a static IP or IP range
** Internal domain name that is routed from an internal DNS server and points to the static IP
** Default storage provider in the Kubernetes cluster that is backed by a Trident storage class to work with ONTAP.

* *Kubernetes version*: A cluster must be running Kubernetes version 1.17 or later.

* *Image type*: The image type for each worker node must be Ubuntu.

* *Image repository*: You must have an existing image repository.

* *Cluster state*: Clusters must be running in a healthy state and have at least one online worker node.

* *Private clusters* If the cluster is private, it must have the https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[master authorized network^] set to allow the Astra IP addresses:
** 54.164.233.140/32
**	3.218.120.204/32
**	34.193.99.138/32

* *Compute and memory requirements*:

* *Trident*: Astra Enterprise requires that Trident version 21.01 or newer already be installed and configured to work with NetApp ONTAP as the storage backend.

== Access to the internet

You should determine whether you have outside access to the internet. If you do not, some functionality might be limited, such as monitoring data from NetApp Cloud Insights, Support data, or Licensing information.

If you do have access to the internet, decide which of the following NetApp systems you will authorize Astra Enterprise to integrate with:

* Cloud Insights for monitoring and metrics
* Active IQ and SmartSolve for supportability
* IPA for license automation


== Supported apps

Astra Enterprise supports all applications running on your Kubernetes clusters. See link:../release-notes/known-limitations.html[Known limitations].

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. link:../learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app].

No matter which type of app that you use with Astra Enterprise, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== License

Astra Enterprise requires an Astra Enterprise license.

If you want to try Astra Enterprise, you can use a 90-day evaluation license.

== Load balancing

Astra Enterprise requires the Kubernetes cluster to have a load balancer installed and configured with an accessible external IP address. In the internal DNS server configuration, you should point the chosen DNS name for Astra Enterprise to the load-balanced IP address.

== Networking

TBD


== Supported web browsers

Astra Enterprise supports recent versions of Firefox, Safari, and Chrome with a minimum resolution of 1280 x 720.

== Integration with your organization's options:

Before you deploy Astra Enterprise, you should determine which internal integrations should occur, including the following:

* Single sign on
* SMTP server for email notifications

If you want to integrate these options, you should obtain the following:

* SSO integration confirmation details
* SMTP server configuration details
