---
sidebar: sidebar
permalink: concepts/user-roles-namespaces.html
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint
summary: Learn about the available types of data protection in Astra Control Center, and how best to use them to protect your apps.
---

= User roles and namespaces
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

Learn about user roles and namespaces in Astra Control, and how you can use them to control access to resources in your organization.

== User roles
You can use roles to control the access users have to resources or capabilities of Astra Control. The following are the user roles in Astra Control:

* A *Viewer* can view resources.
* A *Member* has Viewer role permissions and can manage apps and clusters, unmanage apps, and delete snapshots and backups.
* An *Admin* has Member role permissions and can add and remove any other users except the Owner.
* An *Owner* has Admin role permissions and can add and remove any user accounts.

You can add constraints to a Member or Viewer user to restrict the user to one or more <<Namespaces>>.

== Namespaces

A namespace is a scope you can assign to specific resources within a cluster that is managed by Astra Control. Astra Control discovers a cluster's namespaces when you add the cluster to Astra Control. Once discovered, the namespaces are available to assign as constraints to users. Only members that have access to that namespace are able to use that resource. You can use namespaces to control access to resources using a paradigm that makes sense for your organization; for example, by physical regions or divisions within a company. When you add constraints to a user, you can configure that user to have access to all namespaces or only a specific set of namespaces. You can also assign namespace constraints using namespace labels.

//START HERE
=== Label selectors

There are two types of label selectors that can be used to define an app within a namespace:

Apart from below to know more about labels refer https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

k8 defaults labels that are associated with the apps, for example lets list the defaults labels associated for postgresql app by querying below
k8 commands to list the labels Collapse source
kubectl get statefulset -n <namespace>
NAME         READY   AGE
postgresql   1/1     3d16h
 
kubectl edit statefulset postgresql -n <namespace>
we see the file, under that we have below section has labels
labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.netapp.io/managed-by: astra.netapp.io
    helm.sh/chart: postgresql-11.8.1
Now in Astra we can define an app using the above labels  app.kubernetes.io/name=postgresql,app.kubernetes.io/managed-by=Helm and select the namespace

in which app is installed,

Note - We can add multi labels selector to define an app in Astra  and we can combine the labels using as per below rule "Set-based label requirements allow filtering keys according to a set of values. Three kinds of operators are supported: in,notin and exists (only the key identifier)."

Examples - app.kubernetes.io/name in ("postgresql","mysql") using in operators

app.kubernetes.io/name=postgresql,app.kubernetes.io/managed-by=Helm using multi label selectors

app.kubernetes.io/name notin (postgresql) and ns ta-multiapps-run5 using notin operators

2. Custom labels - this labels are user created for example if user wants to define apps in Astra which runs in production only, then he can tag  the with labels like "apps=production" to app

to add custom labels Collapse source
We need to add labels to below resources for app
 
1. Pods, Statefulset, namespace, pvc, secrets
 
kubectl get statefulset -n <namespace>
NAME         READY   AGE
postgresql   1/1     3d16h
 
kubectl edit statefulset postgresql -n <namespace>
add the label under labels section "apps=production" and save the file.
 
we can check if the labels are added by below command
kubectl get statefulset postgresql -n <> --show-labels
 
The above command can be used to add for remaining resources Pods, namespace, pvc, secrets
Note : just to ensure we have added the custom labels to all the resources  please run the below example query (please modify the ns accordingly based on app)

Commands to check if we have applied custom labels to all resources Collapse source
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind -l ‘app.kubernetes.io/managed-by=Helm,app.kubernetes.io/instance=mariadb’ -n mariadb-ns --ignore-not-found -o name
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind -l <labels> -n <namespace> --ignore-not-found -o name


== Find more information
link:../use/manage-roles.html[Manage roles]
