---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: object store, bucket, s3
summary: Adding object store bucket providers is essential if you want to back up your applications and persistent storage of if you want to clone applications across clusters.
---

= Manage object store buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Adding object store bucket providers is essential if you want to back up your applications and persistent storage of if you want to clone applications across clusters. Using Astra Control, add an object store provider as your backup destination.

You don’t need an object store bucket if you are:

* Cloning your application configuration and persistent storage to the same cluster
* Cloning to a different cluster using an existing backup or snapshot

Use any of the following object store bucket types:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Generic S3

== Add an object store bucket

Admins can add object store buckets. When you use Astra Control to back up or clone your application data, Astra Control stores those backups or clones in the  object store buckets that you define here.

When you add an object store bucket, Astra Control appends a default bucket indicator, such as “bucket-002” to the name.

.Steps

. In the left navigation area, select *Buckets*.
. Select *Add bucket*.
. Select the bucket type.
. Enter the bucket name and optional description.
+
TIP: The bucket name appears as a backup location that you can choose later when you're creating a backup. The name also appears during protection policy configuration.

. Enter the or IP address of the S3 server.
. If you want this bucket to be the default bucket for all backups, check the "Make this bucket the default bucket for this private cloud" option.
+
NOTE: This option does not appear for the first bucket you create.

. Continue by adding credential information.

== Add and remove S3 access credentials

Add or remove S3 access credentials at any time. Astra Control uses these credentials to discover Kubernetes compute and the apps on the compute and to provision resources.

All users in Astra Control share the same set of credentials.

While the most common way to add credentials to Astra Control is when you manage compute, you can also add credentials from the Accounts page or the Buckets page.

These credentials must have the necessary access roles to facilitate application data management.

.Steps

. From the Buckets page, select either the *Add* or *Use existing* tab.
. Enter a name for the credential that distinguishes it from other credentials in Astra Control.
. Enter the access ID and secret key either by uploading the file or by pasting the contents from your clipboard.

== Remove credentials

Remove credentials from an account at any time. You should remove credentials only after unmanaging all compute.

TIP: The first set of credentials that you add to Astra Control is always in use because Astra Control uses the credentials to authenticate the backup bucket. It’s best not to remove these credentials.

.Steps
. Select *Account* > *Credentials*.
.	From the State drop-down list, click the credentials you want to remove.
. Select *Remove*.
.	Type the name of the credentials to confirm deletion and then select *Yes, Remove Credentials*.


== Edit an object store bucket

You can change the access credential information for a bucket and change whether a selected bucket is the default bucket.

.Steps
.	From left navigation, select *Buckets*.
. From the Actions menu, select *Edit*.
. Make changes to the credentials or to the default bucket checkbox.
. Select *Update*.
