---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes
summary: Adding object store bucket providers is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters.
---

= Manage buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

An object store bucket provider is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters. Using Astra Control Center, add an object store provider as your off-cluster, backup destination for your apps.



You don’t need a bucket if you are cloning your application configuration and persistent storage to the same cluster.

// Cloning to a different cluster using an existing backup or snapshot  - requires a bucket.

Use one of the following Amazon Simple Storage Service (S3) bucket providers:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Generic S3
* Microsoft Azure

NOTE: Although Astra Control Center supports Amazon S3 as a Generic S3 bucket provider, Astra Control Center might not support all object store vendors that claim Amazon’s S3 support.

// TIP: Ensure you use a single bucket type; otherwise, mixing bucket types can cause errors.


A bucket can be in one of these states:

* pending: The bucket is scheduled for discovery.
* available: The bucket is available for use.
* removed: The bucket is not currently accessible.

For instructions on how to manage buckets using the Astra Control API, see the link:https://docs.netapp.com/us-en/astra-automation/[Astra Automation and API information^].

You can do these tasks related to managing buckets:

* link:../get-started/setup_overview.html#add-a-bucket[Add a bucket]
* <<Edit a bucket>>
* <<Remove a bucket>>

NOTE: S3 buckets in Astra Control Center do not report available capacity. Before backing up or cloning apps managed by Astra Control Center, check bucket information in the ONTAP or StorageGRID management system.

// DOC-3561

== Remove credentials

Remove S3 credentials from an account at any time using the Astra Control API.

For details, see https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^].


TIP: The first set of credentials that you add to Astra Control is always in use because Astra Control uses the credentials to authenticate the backup bucket. It’s best not to remove these credentials.

//.Steps
//. Select *Account* > *Credentials*.
//.	From the State drop-down list, select the credentials you want to remove.
//. Select *Remove*.
//.	Type the *remove* to confirm deletion and then select *Yes, remove credentials*.


== Edit a bucket

You can change the access credential information for a bucket and change whether a selected bucket is the default bucket.

NOTE: When you add a bucket, select the correct bucket provider and provide the right credentials for that provider. For example, the UI accepts NetApp ONTAP S3 as the type and accepts StorageGRID credentials; however, this will cause all future app backups and restores using this bucket to fail. See the link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures[Release Notes].

.Steps
.	From left navigation, select *Buckets*.
. From the Options menu in the *Actions* column, select *Edit*.
. Change any information other than the bucket type.
+
TIP: You can't modify the bucket type.

. Select *Update*.

== Remove a bucket

You can remove a bucket that is no longer in use or is not healthy. You might want to do this to keep your object store configuration simple and up-to-date.

You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.

.What you'll need

* You should check to ensure that there are no running or completed backups for this bucket before you begin.
* You should check to ensure that the bucket is not being used for any scheduled backups.

If there are, you will not be able to continue.


.Steps
. From left navigation, select *Buckets*.
. From the *Actions* menu, select *Remove*.

+
NOTE: Astra Control ensures first that there are no schedule policies using the bucket for backups and that there are no active backups in the bucket you are about to remove.

. Type "remove" to confirm the action.
. Select *Yes, remove bucket*.

== Find more information

* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^]
