---
sidebar: sidebar
permalink: use/manage-connections.html
keywords: manage package, packages, install
summary: You can upload and install packages to Astra Control Center.
---

= Manage repository connections
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

You can connect repositories to Astra Control to use as a reference for package installation images and upgrade packages. When you install packages, Astra Control imports them from the image repository. When you upgrade Astra Control Center, Astra Control Center pulls the software upgrade package from the artifact repository.

.What you'll need

* Kubernetes cluster with Astra Control Center installed


== Connect a Docker image repository
You can connect a Docker image repository to hold package installation images, such as those for Astra Data Store. When you install packages, Astra Control imports them from the image repository.

.Steps

. In the *Manage Your Account* navigation area, select *Account*.
. Select the *Connections* tab.
. In the *Docker Image Repository* section, select the menu at the top right.
. Select *Connect*.
. Add the URL and port for the repository.
. If authentication is required, enable the *Use authentication* check box and enter the credentials for the repository.
. Select *Connect*.

.Result

The repository is connected. In the *Docker Image Repository* section, the repository should show a connected status.

== Disconnect a Docker image repository
You can remove the connection to a Docker image repository if it is no longer needed.

.Steps

. In the *Manage Your Account* navigation area, select *Account*.
. Select the *Connections* tab.
. In the *Docker Image Repository* section, select the menu at the top right.
. Select *Disconnect*.
. Select *Yes, disconnect Docker image repository*.

.Result

The repository is disconnected. In the *Docker Image Repository* section, the repository should show a disconnected status.


== Connect an artifact repository
You can connect an artifact repository, such as Artifactory, to host Astra Control Center upgrade packages.

.Steps

. In the *Manage Your Account* navigation area, select *Account*.
. Select the *Connections* tab.
. In the *Artifact Repository* section, select the menu at the top right.
. Select *Connect*.
. Add the URL and port for the repository.
. If authentication is required, enable the *Use authentication* check box and enter the credentials for the repository.
. Select *Connect*.

.Result

The repository is connected. In the *Artifact Repository* section, the repository should show a connected status.

== Disconnect an artifact repository
You can remove the connection to an artifact repository if it is no longer needed.

.Steps

. In the *Manage Your Account* navigation area, select *Account*.
. Select the *Connections* tab.
. In the *Artifact Repository* section, select the menu at the top right.
. Select *Disconnect*.
. Select *Yes, disconnect artifact repository*.


.Result

The repository is disconnected. In the *Artifact Repository* section, the repository should show a connected status.
