---
sidebar: sidebar
permalink: use/manage-credentials.html
keywords: invite users, add users, remove users, delete users
summary: Add and remove cloud provider credentials from your account at any time. Astra uses these credentials to provision resources on your behalf.
---

= Add and remove credentials
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Add and remove credentials for local private cloud providers such as ONTAP S3, Kubernetes clusters managed with OpenShift, or unmanaged Kubernetes clusters from your account at any time. Astra Control Center uses these credentials to discover Kubernetes clusters and the apps on the clusters, and to provision resources on your behalf.

Note that all users in Astra Control Center share the same sets of credentials.

== Add credentials

You can add credentials to Astra Control Center when you manage clusters. To add credentials by adding a new cluster, refer to link:../get-started/setup_overview.html#add-cluster[Add a Kubernetes cluster].

IMPORTANT: If you create your own `kubeconfig` file, you should define only *one* context element in it. See https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[Kubernetes documentation^] for information about creating `kubeconfig` files.

== Remove credentials

Remove credentials from an account at any time. You should only remove credentials after link:unmanage.html[unmanaging all associated clusters].

NOTE: The first set of credentials that you add to Astra Control Center is always in use because Astra Control Center uses the credentials to authenticate to the backup bucket. It's best not to remove these credentials.

.Steps

. Select *Account*.
. Select the *Credentials* tab.
. Select the Options menu in the *State* column for the credentials that you want to remove.
. Select *Remove*.
. Type the word "remove" to confirm deletion and then select *Yes, Remove Credential*.

.Result

Astra Control Center removes the credentials from the account.
