---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: object storage, astra, buckets, s3, cr, custom resource
summary: Adding object store bucket providers is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters.
---

= Manage buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
An object store bucket provider is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters. Using Astra Control Center, add an object store provider as your off-cluster, backup destination for your apps.



You don't need a bucket if you are cloning your application configuration and persistent storage to the same cluster.

// Cloning to a different cluster using an existing backup or snapshot  - requires a bucket.

Use one of the following Amazon Simple Storage Service (S3) bucket providers:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Microsoft Azure
* Generic S3
+
NOTE: Amazon Web Services (AWS) and Google Cloud Platform (GCP) use the Generic S3 bucket type.

+
NOTE: Although Astra Control Center supports Amazon S3 as a Generic S3 bucket provider, Astra Control Center might not support all object store vendors that claim Amazon's S3 support.

// TIP: Ensure you use a single bucket type; otherwise, mixing bucket types can cause errors.


A bucket can be in one of these states:

* pending: The bucket is scheduled for discovery.
* available: The bucket is available for use.
* removed: The bucket is not currently accessible.

For instructions on how to manage buckets using the Astra Control API, see the link:https://docs.netapp.com/us-en/astra-automation/[Astra Automation and API information^].

You can do these tasks related to managing buckets:

* link:../get-started/setup_overview.html#add-a-bucket[Add a bucket]
* <<Edit a bucket>>
* <<Set the default bucket>>
* <<Rotate or remove bucket credentials>>
* <<Remove a bucket>>
* <<Manage a bucket using a custom resource>>

NOTE: S3 buckets in Astra Control Center do not report available capacity. Before backing up or cloning apps managed by Astra Control Center, check bucket information in the ONTAP or StorageGRID management system.

// DOC-3561


== Edit a bucket

You can change the access credential information for a bucket and change whether a selected bucket is the default bucket.

NOTE: When you add a bucket, select the correct bucket provider and provide the right credentials for that provider. For example, the UI accepts NetApp ONTAP S3 as the type and accepts StorageGRID credentials; however, this will cause all future app backups and restores using this bucket to fail. See the link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures[Release Notes].

.Steps
. From the left navigation, select *Buckets*.
. From the menu in the *Actions* column, select *Edit*.
. Change any information other than the bucket type.
+
TIP: You can't modify the bucket type.

. Select *Update*.

== Set the default bucket
When you perform a clone across clusters, Astra Control requires a default bucket. Follow these steps to set a default bucket for all clusters.

.Steps

. Go to *Cloud instances*.
. Select the menu in the *Actions* column for the cloud instance in the list.
. Select *Edit*.
. In the *Bucket* list, select the bucket you want to be the default.
. Select *Save*.

== Rotate or remove bucket credentials
Astra Control uses bucket credentials to gain access and provide secret keys for an S3 bucket so that Astra Control Center can communicate with the bucket.

=== Rotate bucket credentials

If you rotate credentials, rotate them during a maintenance window when no backups are in progress (scheduled or on-demand).

.Steps to edit and rotate credentials

. From the left navigation, select *Buckets*.
. From the Options menu in the *Actions* column, select *Edit*.
. Create the new credential.
. Select *Update*.


//.Steps
//. Select *Account* > *Credentials*.
//.	From the State drop-down list, select the credentials you want to remove.
//. Select *Remove*.
//.	Type the *remove* to confirm deletion and then select *Yes, remove credentials*.

=== Remove bucket credentials

You should remove bucket credentials only if new credentials have been applied to a bucket, or if the bucket is no longer actively used.


TIP: The first set of credentials that you add to Astra Control is always in use because Astra Control uses the credentials to authenticate the backup bucket. Do not remove these credentials if the bucket is in active use as this will lead to backup failures and backup unavailability.

NOTE: If you do remove active bucket credentials, see https://kb.netapp.com/Cloud/Astra/Control/Deleting_active_S3_bucket_credentials_leads_to_spurious_500_errors_reported_in_the_UI[troubleshooting bucket credential removal].

For instructions on how to remove S3 credentials using the Astra Control API, see the link:https://docs.netapp.com/us-en/astra-automation/[Astra Automation and API information^].


//.Steps
//. Select *Account* > *Credentials*.
//.	From the State drop-down list, select the credentials you want to remove.
//. Select *Remove*.
//.	Type the *remove* to confirm deletion and then select *Yes, remove credentials*.



== Remove a bucket

You can remove a bucket that is no longer in use or is not healthy. You might want to do this to keep your object store configuration simple and up-to-date.

[NOTE]
===============================
* You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.
* You cannot remove a write once read many (WORM) bucket before the bucket's cloud provider retention period has expired. WORM buckets are denoted with "Locked" next to the bucket name.
===============================

* You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.

.Before you begin

* You should check to ensure that there are no running or completed backups for this bucket before you begin.
* You should check to ensure that the bucket is not being used in any active protection policy.

If there are, you will not be able to continue.


.Steps
. From left navigation, select *Buckets*.
. From the *Actions* menu, select *Remove*.
+
NOTE: Astra Control ensures first that there are no schedule policies using the bucket for backups and that there are no active backups in the bucket you are about to remove.

. Type "remove" to confirm the action.
. Select *Yes, remove bucket*.

== Manage a bucket using a custom resource

You can add a bucket using the an Astra Control custom resource (CR) on the application cluster. Adding object store bucket providers is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters. Astra Control stores those backups or clones in the object store buckets that you define. If you are using the custom resource method, application snapshots functionality requires a bucket.

You don't need a bucket in Astra Control if you are cloning your application configuration and persistent storage to the same cluster. 

The bucket custom resource for Astra Control is known as an AppVault. This CR contains the configurations necessary for a bucket to be used in protection operations.

.Before you begin

* Ensure you have a bucket that is reachable from your clusters managed by Astra Control Center.
* Ensure you have credentials for the bucket.
* Ensure the bucket is one of the following types:

** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure
** Generic S3

NOTE: Amazon Web Services (AWS) and Google Cloud Platform (GCP) use the Generic S3 bucket type.

NOTE: Although Astra Control Center supports Amazon S3 as a Generic S3 bucket provider, Astra Control Center might not support all object store vendors that claim Amazon's S3 support.

.Steps

. Create the custom resource (CR) file and name it `astra_appvault.yaml`.

. Configure the following attributes:
+
* *metadata.name*: The name of the AppVault custom resource.
* *spec.prefix*: An optional path that is prefixed to the names of all entities stored in the AppVault.
* *spec.providerConfig*: Stores the configuration necessary to access the AppVault using the specified provider. This field is required.
* *spec.providerCredentials*: Stores references to any credential required to access the AppVault using the specified provider. `valueFromSecret` is required.
** *spec.valueFromSecret*: Indicates that the credential value should come from a secret. `key` and `name` are required.
*** *key*: The valid key of the secret to select from.
*** *name*: Name of the secret containing the value for this field. Must be in the same namespace.
* *spec.providerType*: Determines what provides the backup, e.g., S3 or FileSystem. This field is required.
+
Example YAML:
+
[source,yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra_appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----

. After you populate the `astra_appvault.yaml` file with the correct values, apply the CR:
+
[source,console]
----
kubectl apply -f astra_appvault.yaml
----
+
NOTE: When you add a bucket, Astra Control marks one bucket with the default bucket indicator. The first bucket that you create becomes the default bucket. As you add buckets, you can later decide to link:../use/manage-buckets.html#set-the-default-bucket[set another default bucket^].


== Find more information

* https://docs.netapp.com/us-en/astra-automation[Use the Astra Control API^]
