---
sidebar: sidebar
permalink: use/protect-acc-with-acc.html
keywords: backup astra control center, restore astra control center
summary: You can backup and restore Astra Control Center using a secondary Astra Control Center instance or with Astra replication if the underlying storage is using ONTAP.
---

= Protect Astra Control Center using Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
You can backup the Astra Control Center application to better ensure resiliency against fatal errors on the Kubernetes cluster where Astra Control Center is running. You can backup and restore Astra Control Center using a secondary Astra Control Center instance or with Astra replication if the underlying storage is using ONTAP.

In this scenario, a second instance of Astra Control Center is deployed and configured in a different fault domain and runs on a different Kubernetes cluster than the primary Astra Control Center instance. The second Astra Control instance is used to back up and potentially restore the primary Astra Control Center instance. A restored Astra Control Center instance will continue to provide application data management for the application cluster applications and restore accessibility to backups and snapshots of those applications.

.Before you begin

Ensure that you have the following before setting up protection scenarios for Astra Control Center:

* *A Kubernetes cluster running the primary Astra Control Center instance*: This cluster hosts the primary Astra Control Center instance which manages application clusters.
* *A second Kubernetes cluster running the secondary Astra Control Center instance*: This cluster hosts the Astra Control Center instance that manages the primary Astra Control Center instance.
* *A third Kubernetes cluster of the same Kubernetes distribution type as the primary*: This cluster will host the restored or replicated instance of Astra Control Center. It must have the same Astra Control Center namespace available that is currently deployed on the primary. For example, if Astra Control Center is deployed in namespace `netapp-acc` on the source cluster, the namespace `netapp-acc` must be available and not used by any applications on the destination Kubernetes cluster. 
* *S3-compatible buckets*: Each Astra Control Center instance has an accessible S3-compatible object storage bucket.
* *A configured load balancer*: The load balancer provides an IP address for Astra and must have network connectivity to the application clusters and both S3 buckets.
* *Clusters meet Astra Control Center requirements*: https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements [Each cluster used in Astra Control Center protection meets general Astra Control Center requirements]

.About this task

These procedures describe the necessary steps to restore Astra Control Center to a new cluster using either <<Backup and restore Astra Control Center,backup and restore>> or <<Protect Astra Control Center using Replication,replication>>. Steps are based on the example configuration depicted here: 

//<Image>

In this example configuration, the following is shown:

* *A Kubernetes cluster running the primary Astra Control Center instance*: 
** OpenShift cluster: ocp-app-qa4
** Astra Control Center primary instance: app-lb-15.rtp.openenglab.netapp.com
* *The second Kubernetes cluster running the secondary Astra Control Center instance*: 
** OpenShift cluster: ocp-app-qa2 
** Astra Control Center secondary instance: app-lb-14.rtp.openenglab.netapp.com
** This cluster will be used for the backup and to provide temporary app data management for ocp-app-qa4 cluster.
* *A third Kubernetes cluster of the same Kubernetes distribution type as the primary that will be used for restore*: 
** OpenShift cluster: ocp-app-qa1
** This cluster will be used for the restore.

Not depicted in the diagram:

* All the clusters have ONTAP backends with Trident installed. 
* OpenShift clusters are using MetalLB as the load balancer. * The snapshot controller and volumeSnapshotClass are also installed on all the clusters as outlined in the prerequisites. 

NOTE: Additionally, ocp-app-qa4 could have applications that are being managed by the primary or secondary Astra Control Center instance. They are not shown here for brevity. 

 
== Backup and restore Astra Control Center

This procedure describes the necessary steps to restore Astra Control Center to a new cluster using backup and restore or replication. 

In this example, Astra Control Center is always installed under the `netapp-acc` namespace and the operator is installed under the `netapp-acc-operator` namespace. 
+
NOTE: Although not described, Astra Control Center operator can also be deployed in the same namespace as the Astra CR.

.Before you begin

* You have installed the primary Astra Control Center on a cluster.
* You have installed the secondary Astra Control Center on a different cluster.

.Steps

. Manage the primary Astra Control Center application and destination cluster from the secondary Astra Control Center instance:
.. Log into the secondary Astra Control Center instance. 
.. link:../get-started/setup_overview.html#add-cluster[Add the primary Astra Control Center cluster] (ocp-app-qa4). 
.. link:../get-started/setup_overview.html#add-cluster[Add the destination cluster] (ocp-app-qa1) that will be used for the restore.

. Manage Astra Control Center and the Astra Control Center operator on the secondary Astra Control Center:
.. From the Applications page, select *Define*.
.. In the *Define application* window, enter the app name (`netapp-acc`).
.. Choose the cluster that is running the primary Astra Control Center (`ocp-app-qa4`) from the *Cluster* drop-down list.
.. Choose the `netapp-acc` namespace for Astra Control Center from the *Namespace* drop-down list.
.. Select *Next*.
.. On the Cluster Resources page, check *Include additional cluster-scoped resources*.
.. Select *Add include rule*.
.. Select the entries shown here, and select *Add*:

//<Image>

.. Select *Next*.
.. Confirm the application information.
.. Select *Define*. 
+
After you select *Define*, repeat the Define App process for netapp-acc-operator and select the `netapp-acc-operator` namespace in the Define Application window.

. Back up Astra Control Center and the operator:
.. On the secondary Astra Control Center, navigate to the Applications page by selecting the Applications tab.
.. Back up the Astra Control Center application (`netapp-acc`).
.. Back up the operator (`netapp-acc-operator).

. After you have backed up Astra Control Center and the operator, simulate a disaster recovery (DR) scenario by link:../use/uninstall_acc.html[uninstalling Astra Control Center^] from the primary cluster.
+
NOTE: You will restore Astra Control Center to a new cluster (the third Kubernetes cluster described in this procedure) and use the same DNS or IP addresses for the newly installed Astra Control Center.

. Using the secondary Astra Control Center, link:../use/restore-apps.html[restore^] the primary instance of the Astra Control Center application from its backup:
.. Select *Applications* and then select the name of an app.
.. From the Options menu in the Actions column, select *Restore*.
.. Choose the *Restore to original namespaces* as the restore type.
.. Enter the restore name (`netapp-acc`).
.. Choose the destination cluster (`ocp-app-qa1`).
.. Enter the namespace so that it is the same namespace as the original.
.. On the Restore Source page, select the application backup that will be used as the restore source.
.. Select *Restore using original storage classes*.
.. Select *Restore all resources*.
.. Review restore information, and then select *Restore* to start the restore process that restores Astra Control Center to the destination cluster (`ocp-app-qa1`). The restore is complete when the application enters `available` state.

. Configure Astra Control Center on the destination cluster:
.. Open a terminal and connect using kubeconfig to the destination cluster (`ocp-app-qa1`) that contains the restored Astra Control Center.
.. Edit the Astra Control Center custom resource (CR):
+
----
kubectl edit acc -n netapp-acc
----

.. Change the DNS name under `spec:` to match the primary cluster's Astra Control Center DNS name.
.. Determine the IP address of the primary cluster's Astra Control Center DNS name:
+
----
nslookup <primary cluster's DNS name>
----

. Update your ingress configurations so that the primary cluster's IP address is set as the IP address used by your ingress:
+
NOTE: There are many ingress methods you might have link:../get-started/install_acc.html#set-up-ingress-for-load-balancing[set up] for load balancing. Updating the IP address may vary from these steps depending on the type of ingress used. This example describes updating the IP address for MetalLB. 

.. Edit configuration: 
+
----
kubectl edit ipaddresspool.metallb.io/first-pool -n metallb-system
----

.. Replace the IP address in the `spec/addresses:` section with the IP address that nslookup returned in the previous step.
.. Save the deployment (`:wq`).
.. Restart the controller: 
+
----
kubectl rollout restart deployment controller -n metallb-system
----

.. Skip to the "Restore the Astra Control Center Operator" section of this document to complete the restore process.

== Protect Astra Control Center using Replication

This procedure describes the necessary steps to configure link:../use/replicate_snapmirror.html[Astra Control Center replication^] to protect the primary Astra Control Center instance.

In this example, Astra Control Center is always installed under the `netapp-acc` namespace and the operator is installed under the `netapp-acc-operator` namespace. 

.Before you begin

* You have installed the primary Astra Control Center on a cluster.
* You have installed the secondary Astra Control Center on a different cluster.

.Steps

. Manage the primary Astra Control Center application and destination cluster from the secondary Astra Control Center instance:
.. Log into the secondary Astra Control Center instance. 
.. link:../get-started/setup_overview.html#add-cluster[Add the primary Astra Control Center cluster] (ocp-app-qa4). 
.. link:../get-started/setup_overview.html#add-cluster[Add the destination cluster] (ocp-app-qa1) that will be used for the restore.

. Manage Astra Control Center and the Astra Control Center operator on the secondary Astra Control Center:
.. Select *Clusters* and select the cluster that contains the primary Astra Control Center (`ocp-app-qa4`).
.. Select the *Namespaces* tab.
.. Select `netapp-acc` and `netapp-acc-operator` namespaces.
.. Select the Actions menu for one of these and select *Define as application*.
.. Select *View in applications* to see the defined application.

. Configure Backends for Replication:
Replication requires that the primary Astra Control Center cluster and the destination cluster use two different peered ONTAP storage backends assigned to each cluster.
Once they are peered, they will appear on the Backends page of the UI under the "Discovered" tab.

Manage both peered backends.


 Step 4: Configure Replication
On the Applications screen, click on the "netapp-acc" application.

 
Click on "Configure replication policy"

Select "ocp-app-qa1" as the destination.
Select the storage class.
Enter "netapp-acc" as the destination namespace.
Change the replication frequency if desired.
Click "Next"

Confirm the configuration is correct, click "Save"

The replication will transition from "Establishing" to "Established".
 
While this replication is active it will replicate every 5 minutes until the replication configuration is deleted.

Step 5: Failover the Replication

If the primary system is corrupted or no longer accessible, we can now do a failover to the other cluster.
NOTE: Make sure the destination cluster does not have Astra Control Center installed to ensure a successful failover.?? Need to confirm this.
Click on the ellipse and select "Fail over".


Click the "Fail over" button to start the failover process:

The status will change to "Failing over" and will soon change to "Failed over".





Step 6: Complete the failover configuration
Open a terminal and connect via the new cluster's kubeconfig that has Astra Control Center installed.
Run the following command: "kubectl edit acc -n netapp-acc"
Change the "astraAddress" under the "spec:" section in this configuration file to the destination DNS address
Re-run "kubectl get acc -n netapp-acc" and confirm that the Address has been updated.
Confirm that all required traefik CRDs are present: "kubectl get crds | grep traefik" (NOTE: the containo* CRDs may be removed in Astra version 23.08).

If some of the above CRDs are missing:
Go to this page: https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/
Copy the "Definitions" area into a file.
Run the following command: "kubectl apply -f <file name>"
Run this command to restart traefik (this assumes Astra Control Center is deployed in the netapp-acc namespace): "kubectl get pods -n netapp-acc | grep -e "traefik" | awk '{print $1}' | xargs kubectl delete pod -n netapp-acc"
Ingress configurations
There are several methods to set up Ingress for load balancing: https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html#set-up-ingress-for-load-balancing. 

For this process, the Ingress/Loadbalancer that holds IP address needs to be restarted because the Astra Control Center DNS address was updated.  

The below example describes how Metallb would be restarted. 

Run the following command: "kubectl edit ipaddresspool.metallb.io/first-pool  -n metallb-system"
Confirm the IP address in the "spec/addresses:" section is the IP address of the destination cluster, save the deployment (:wq)
Regardless if metallb needed updating, restart metallb: "kubectl rollout restart deployment controller -n metallb-system" 
Proceed to the "Restore the Astra Control Center Operator" section below.



Restore the Astra Control Center Operator

Using the secondary Astra Control Center, restore the primary Astra Control Center operator from the backup as depicted below. The destination namespace must be the same as the source namespace. In the case where Astra Control Center was deleted from the source cluster, the backups will still exist and perform the same steps.




Choose the destination cluster and change the namespace to be the same namespace as the source.

 

Select the backup that was taken earlier:
 


Select "Restore using original storage classes"


Select "Restore all resources"



Review then click on "Restore" to start the restore process:
 

The UI will show the Astra Control Center operator being restored to the destination cluster (ocp-app-qa1) and will eventually become "Available".
Within ten minutes, the DNS address should resolve in the UI.



Troubleshooting
If unable to connect to the UI, the following commands may help diagnose the issue.

"kubectl get pods -n netapp-acc" – confirm that all pods are up and running. If some pods are in the "CrashLookBackOff" state, try restarting them and they should transition to the "Running" state.
"kubectl get acc -n netapp-acc" to confirm the Astra Control Center system is in the ready state:
NAME UUID VERSION ADDRESS READY
astra 89f4fd47-0cf0-4c7a-a44e-43353dc96ba8 23.07.0-24 app-lb-15.rtp.openenglab.netapp.com True

"kubectl describe acc astra -n netapp-acc" – shows the Astra Control Center deployment informationan. The "Deployment State" should be in the "Deployed" state
Restart traefik:
"kubectl get pods -n netapp-acc | grep -e "traefik" | awk '{print $1}' | xargs kubectl delete pod -n netapp-acc"
Restart the Load Balancer. 
If using metallb:   "kubectl rollout restart deployment controller -n metallb-system" 
Conclusion
Astra Control Center, its registered clusters and managed applications with their snapshots and backups are now available on the destination cluster. Any protection policies you had on the original are also there on the new instance. You can continue to take scheduled or on-demand backups and snapshots.
