---
sidebar: sidebar
permalink: use/protect-acc-with-acc.html
keywords: backup astra control center, restore astra control center
summary: 
---

= Protect Astra Control Center using Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Astra Control Center can itself be backed up as protection against a fatal error on a Kubernetes cluster where Astra Control Center is running. In this case, another instance of Astra Control Center  can be deployed and configured in a different fault domain to protect the primary Astra Control Center  instance. The new Astra Control Center  instance should be run on a different Kubernetes cluster than the primary and it is used to back up and potentially restore the primary Astra Control Center  instance. The restored Astra Control Center  instance will continue to provide application data management for the application cluster applications and restore accessibility to previous backups and snapshots of those applications.

This document outlines the procedure used to backup and restore a primary Astra Control Center  instance..

.About this task

Astra Control Center  can be deployed with two methods and both methods are covered in this document:
•	Deploy the operator in a different namespace than the Astra Custom Resource
•	Deploy the operator in the same namespace as the Astra Custom Resource
This procedure uses the example setup depicted below. In this case, the secondary Astra Control Center  instance (app-lb-14.rtp.openenglab.netapp.com) is deployed on the Openshift cluster called ocp-app-qa2 and will be used to provide the application data management for the ocp-app-qa4 cluster. The ocp-app-qa4 cluster is running the primary Astra Control Center  instance (https://app-lb-15.rtp.openenglab.netapp.com/), managing the application clusters. Although not depicted in the diagram, all the clusters have ONTAP backends with Trident installed. The Openshift clusters are using Metallb as the load balancer. The snapshot controller and volumeSnapshotClass is also installed on all the clusters as outlined in the prerequisites. Additionally, ocp-app-qa4 could have applications that are being managed by the primary or secondary Astra Control Center  instance. They are not shown here for brevity. 

This procedure will outline steps necessary to backup and restore Astra Control Center  to a new cluster. 
The below screenshots are taken from release 23.04.
The steps in this procedure use the above example setup and backup Astra Control Center  on the ocp-app-qa4 cluster and restore Astra Control Center  onto the ocp-app-qa1cluster. 
In this example, Astra Control Center  is always installed under the netapp-acc namespace and the operator is installed under the netapp-acc-operator namespace.


.Before you begin

The following is required to backup and restore ACC. All clusters must have the prerequisites as described by the Astra Control documentation. All Astra Control Center  instances must have an accessible S3 compatible object storage bucket.  

* A Kubernetes cluster running the primary Astra Control Center  instance: This cluster hosts the primary Astra Control Center  instance which manages application clusters.
* A Kubernetes cluster running the secondary Astra Control Center  instance: This cluster hosts the Astra Control Center  instance that manages the primary Astra Control Center  instance.
* A Kubernetes cluster of the same Kubernetes distribution type as the primary: This cluster will host the restored instance of ACC. It must have the same Astra Control Center  namespace available as currently deployed on the primary. For example, if Astra Control Center  is deployed in namespace netapp-acc on the source cluster, the namespace netapp-acc must be available (not used) on the destination Kubernetes cluster. A load balancer must also be configured to provide an IP address for Astra and must have network connectivity to the application clusters and both S3 buckets.

.Steps

Step 1: Manage the Primary Astra Control Center  Application and Destination Cluster from Secondary Astra Control Center  instance
After the primary and secondary Astra Control Center  instances are installed per the documentation, log into the secondary Astra Control Center  instance and manage the primary Astra Control Center  cluster (ocp-app-qa4 in the below image) and the destination cluster (ocp-app-qa1). 

  

Step 2: Manage Astra Control Center  and the Astra Control Center  Operator 
On the secondary ACC:
•	Click on the “Applications” tab on the left, then click “Define”
•	Select the cluster that the primary Astra Control Center  is on (e.g. ocp-app-qa4)
•	Find “netapp-acc” in the dropdown
•	Click on “Next”


•	On the “Cluster Resources” page, select the “include additional cluster-scoped resources” checkbox, then click on “+ Add include rule”
•	Select the below entries, click “Add”

 
•	Click “Next”, confirm the “Review Application Information” screen is correct, then click “Define”.
•	Perform the same steps for the netapp-acc-operator.

Step 3: Backup Astra Control Center  and the operator 

On the secondary ACC, navigate to the Applications screen by selecting the Applications tab to the left
If the user clicks on each application, they can set up a protection policy that includes a backup schedule – which create backups of the Astra Control Center  applications on a regular basis.
Or the user can create an on-demand backup.  To create an on-demand backup, click on the ellipsis on the right side of the Application screen above, and select “Back up”. 
Backup Astra Control Center  (netapp-acc in below screenshot) then the netapp-acc-operator.

 
Step 4: Configure the Disaster Recovery (DR) scenario

Now that Astra Control Center  and the operator are backed up, to simulate a DR scenario, uninstall the primary Astra Control Center  system.
Procedure here: https://docs.netapp.com/us-en/astra-control-center/use/uninstall_acc.html
The reason for doing this is because we are going to restore Astra Control Center  to a new cluster and use the exact same DNS/IP addresses for the newly installed ACC. 

Step 5: Restore Astra Control Center  from Backup 

Using the secondary ACC, restore the primary Astra Control Center  application from the backup as depicted below. The destination namespace must be the same as the source namespace. In the case where Astra Control Center  was deleted from the source cluster, the backups will still exist and perform the same steps.

 

Choose the destination cluster and change the namespace to be the same namespace as the source.
 

Select the backup that was taken earlier:
 


Select “Restore using original storage classes”
 


Select “Restore all resources”
 

Review then click on “Restore” to start the restore process:
 

It will show Astra Control Center  being restored to the destination cluster (ocp-app-qa1) and will eventually become “Available”.

 
 

Step 6: Confirm the Astra Control Center  Restore ran correctly and configure if needed 

1.	Open a terminal and connect to the new cluster that has Astra Control Center  installed.
2.	Run the following command to confirm the DNS is correct:  kubectl get acc -n netapp-acc:
 
Note how the DNS address is identical to the Astra Control Center  system it was restored from.
3.	If this isn’t the case, run the following command:  kubectl edit acc -n netapp-acc
a.	Then change the DNS name under “spec:” to match what the primary system’s DNS name is.
4.	Run “nslookup <above DNS name> to determine the IP address that the DNS address resolves to
5.	Configure the load balancer to point to the primary system’s IP address.  

If running metallb as the load balancer:
a.	Run the following command: “kubectl edit ipaddresspool.metallb.io/first-pool  -n metallb-system”
b.	Replace the two IP addresses with the IP address that nslookup returned and save the deployment (:wq)
c.	Run the following command: “kubectl rollout restart deployment controller -n metallb-system”
6.	Within a minute or two and the DNS address should resolve in the UI.

Step 7: Restore the Astra Control Center  Operator 

Using the secondary ACC, restore the primary Astra Control Center  operator from the backup as depicted below. The destination namespace must be the same as the source namespace. In the case where Astra Control Center  was deleted from the source cluster, the backups will still exist and perform the same steps.

 

Choose the destination cluster and change the namespace to be the same namespace as the source.
 

Select the backup that was taken earlier:
 


Select “Restore using original storage classes”
 


Select “Restore all resources”
 

Review then click on “Restore” to start the restore process:
 

It will show the Astra Control Center  operator being restored to the destination cluster (ocp-app-qa1) and will eventually become “Available”.

Step 8: Confirm the Operator and the Astra Control Center  CR are reconciled. 

Because we can connect to the UI above, most likely the system is up and running.  But it’s good to double-check the following to ensure the system is healthy.
Run the following command and confirm the operator is running:  “kubectl get pods -A | grep netapp-acc-operator” 
Then run the following command:  “kubectl describe acc astra -n netapp-acc” and confirm the deployment state is deployed.

----
[tme@localhost$ kubectl describe acc astra -n netapp-acc
Name:         astra
Namespace:    netapp-acc
Labels:       app.netapp.io/managed-by=astra.netapp.io
Annotations:  <none>
API Version:  astra.netapp.io/v1
Kind:         AstraControlCenter
…
Conditions:
    Last Transition Time:  2022-03-11T19:07:55Z
    Message:               Astra is deployed
    Reason:                Complete
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-03-11T19:07:55Z
    Message:               Deploying succeeded.
    Reason:                Complete
    Status:                False
    Type:                  Deploying
    Last Transition Time:  2022-03-11T19:07:53Z
    Message:               Post Install was successful
    Observed Generation:   1
    Reason:                Complete
    Status:                True
    Type:                  PostInstallComplete
    Last Transition Time:  2022-03-11T19:07:55Z
    Message:               Astra is deployed
    Reason:                Complete
    Status:                True
    Type:                  Deployed
  Deployment State:        Deployed
----


Potential Issues: 
If some Astra Control Center  pods are showing CrashLoopBackOff for several minutes, simply delete those pods.  These pods will restart and should transition into the “Running” state.

Conclusion: 

Astra Control Center, its registered clusters and managed applications with their snapshots and backups are now available on the destination cluster. Any protection policies you had on the original is also there on the new instance. You can continue to take scheduled or on-demand backups and snapshots. If the original Astra Control Center  instance is still there on the source cluster, it can be deleted. 
