---
sidebar: sidebar
permalink: use/protection-overview.html
keywords: backup, back up, backup apps, back up apps, snapshots, snapshot an app, take a snapshot, take a backup, view backups, view snapshots, set policy, set schedule, schedule backups, schedule snapshots
summary: Learn about the available types of data protection in Astra Control Center, and how best to use them to protect your apps.
---

= Protection overview
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Learn about the available types of data protection in Astra Control Center, and how best to use them to protect your apps.

// Describe snapshots, backups, protection policy, and clone/migrate and when you'd use each.

== Snapshots, backups, and protection policies

A _snapshot_ is a point-in-time copy of an app that's stored on the same provisioned volume as the app. They are usually fast. Local snapshots are used to restore the application to an earlier point in time. Snapshots are useful for fast clones; snapshots include all of the Kubernetes objects for the app, including configuration files.

A _backup_ is stored in the external object store. A backup can be slower to take compared to local snapshots. You can migrate an app by restoring its backup to a different cluster. You can also choose a longer retention period for backups. Backups generally offer you better protection than snapshots in cases of server failure or data loss.

A _protection policy_ is a way to protect your apps by automatically creating snapshots, backups, or both according to a schedule that you define. A protection policy also enables you to choose how many snapshots and backups to retain in the schedule. Automating your backups and snapshots with a protection policy is the best way to ensure your apps are protected according to the needs of your organization.

CAUTION: _You can't be fully protected until you have a recent backup_. This is important because backups are stored in an object store away from the persistent volumes. If a failure or accident wipes out the cluster and its associated persistent storage, then you need a backup to recover. A snapshot would not enable you to recover.

== Clones

A _clone_ is an exact duplicate of an app, its configuration, and its persistent storage. You can manually create a clone on either the same Kubernetes cluster or on another cluster. Cloning an app can be useful if you need to move applications and storage from one Kubernetes cluster to another.
