---
sidebar: sidebar
permalink: use/uninstall_acc.html
keywords: astra, astra control center, uninstall, remove
summary: Describes how to remove Astra Control Center and the Astra Control Center Operator.
---

= Uninstall Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
You might need to remove Astra Control Center components if you are upgrading from a trial to a full version of the product. To remove Astra Control Center and the Astra Control Center Operator, run the commands described in this procedure in sequence.

If you have any issues with the uninstall, see <<Troubleshooting uninstall issues>>.

.Before you begin

. link:../use/unmanage.html#unmanage-an-app[Unmanage all apps^] on the clusters.
. link:../use/unmanage.html#unmanage-a-cluster[Unmanage all clusters^].

.Steps

. Delete Astra Control Center. The following sample command is based upon a default installation. Modify the command if you made custom configurations.
+
----
kubectl delete -f astra_control_center.yaml -n netapp-acc
----
+
Result:
+
----
astracontrolcenter.astra.netapp.io "astra" deleted
----

. Use the following command to delete the `netapp-acc` (or custom-named) namespace:
+
----
kubectl delete ns [netapp-acc or custom namespace]
----
+
Example result:
+
----
namespace "netapp-acc" deleted
----

. Use the following command to delete Astra Control Center operator system components:
+
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Result:
+
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----

== Troubleshooting uninstall issues

Use the following workarounds to address any problems you have with uninstalling Astra Control Center.

=== Uninstall of Astra Control Center fails to clean up the monitoring-operator pod on the managed cluster
//DOC-3530/ASTRACTL-9496/Q2 and PI4/PI5
If you did not unmanage your clusters before you uninstalled Astra Control Center, you can manually delete the pods in the netapp-monitoring namespace and the namespace with the following commands:

.Steps
. Delete `acc-monitoring` agent:
+
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
Result:
+
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Delete the namespace:
+
----
kubectl delete ns netapp-monitoring
----
Result:
+
----
namespace "netapp-monitoring" deleted
----
. Confirm resources removed:
+
----
kubectl get pods -n netapp-monitoring
----
Result:
+
----
No resources found in netapp-monitoring namespace.
----
. Confirm monitoring agent removed:
+
----
kubectl get crd|grep agent
----
+
Sample result:
+
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----

. Delete custom resource definition (CRD) information:
+
----
kubectl delete crds agents.monitoring.netapp.com
----
+
Result:
+
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----

=== Uninstall of Astra Control Center fails to clean up Traefik CRDs
//ASTRACTL-9180/DOC-3630/Q2 and PI4/PI5
You can manually delete the Traefik CRDs. CRDs are global resources, and deleting them might impact other applications on the cluster.

.Steps
. List Traefik CRDs installed on the cluster:
+
----
kubectl get crds |grep -E 'traefik'
----
+
Response
+
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----

. Delete the CRDs:
+
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----

== Find more information

* link:../release-notes/known-issues.html[Known issues for uninstall]
