---
sidebar: sidebar
permalink: use/uninstall_acc.html
keywords: astra, astra control center, uninstall, remove
summary: Describes how to remove Astra Control Center and the Astra Control Center Operator.
---

= Uninstall Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You might need to remove Astra Control Center components if you are upgrading from a trial to a full version of the product. To remove Astra Control Center and the Astra Control Center Operator, run the commands described in this procedure in sequence.

.What you'll need

* Use Astra Control Center UI to unmanage all link:../use/unmanage.html#stop-managing-compute[clusters]. 

.Steps

. Delete Astra Control Center. The following sample command is based upon a default installation. Modify the command if you made custom configurations.
+
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Result:
+
----
astracontrolcenter.astra.netapp.io "astra" deleted
----

. Use the following command to delete the `netapp-acc` namespace:
+
----
kubectl delete ns netapp-acc
----
+
Result:
+
----
namespace "netapp-acc" deleted
----

. Use the following command to delete Astra Control Center operator system components:
+
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Result:
+
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----

== Find more information

* link:../release-notes/known-issues.html[Known issues for uninstall]
