---
sidebar: sidebar
permalink: use/unmanage.html
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster, kubernetes, astra, astra control
summary: Remove any apps or compute that you no longer want to manage from Astra Control.
---

= Unmanage apps and compute
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Remove any apps or compute that you no longer want to manage from Astra Control.

== Stop managing an app

Stop managing apps that you no longer want to back up, snapshot, or clone from Astra Control.

* Any existing backups and snapshots will be deleted.

* Applications and data remain available.

.Steps

. From the left navigation bar, select *Apps*.
. Select the checkbox for the apps that you no longer want to manage.
. From the *Action* menu, select *Unmanage*.
. Type "unmanage" to confirm.
. Confirm that you want to unmanage the apps and then select *Yes, Unmanage Application*.


.Result

Astra Control stops managing the app.

== Stop managing compute

Stop managing the compute that you no longer want to manage from Astra Control.

* This action stops your compute from being managed by Astra Control. It doesn't make any changes to the cluster's configuration and it doesn't delete the cluster.

* Trident won't be uninstalled from the cluster. https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/managing.html#uninstalling-trident[Learn how to uninstall Trident^].

.Steps

. From the left navigation bar, select *Compute*.

. Select the checkbox for the compute that you no longer want to manage.

. From the *Actions* menu, select *Unmanage compute/s*.

. Confirm that you want to unmanage the compute and then click *Yes, Unmanage Compute*.

.Result

Astra Control stops managing the compute.
