---
sidebar: sidebar
permalink: use/update_licenses.html
keywords: manage, licenses, licensing, Astra Control Center, add license, update license
summary: You can convert an evaluation license to a full license, or you can update an existing evaluation or full license with a new license.
---

= Update an existing license
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can convert an evaluation license to a full license, or you can update an existing evaluation or full license with a new license. If you don't have a full license, work with your NetApp sales contact to obtain a full license and serial number.

.Steps

. Log in to the NetApp Support Site.
. Access the Astra Control Center Download page, enter the serial number, and download the full NetApp license file (NLF).
. Log in to the Astra Control Center UI.
. From the left navigation, select *Account* > *License*.
. In the *Account* > *License* page, click the status drop-down menu for the existing license and select *Replace*.
. Browse to the license file that you downloaded.
. Select *Add*.

The *Account* > *Licenses* page displays the license information, expiration date (for evaluation licenses), license serial number, cluster ID, and CPU units used.
