---
sidebar: sidebar
permalink: use/upgrade-trident.html
keywords: astra trident upgrade, upgrade trident, Astra Control Provisioner, trident
summary: To upgrade Astra Trident for use with Astra Control Center, you'll follow the steps described to update the bundle from Trident.
---

= Upgrade Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Upgrade your Astra Trident to a version supported for use with Astra Control Center. 23.10 and later versions of Astra Trident include the Astra Control Provisioner, which allows licensed Astra users access to closed-source Trident functionality.

link:../get-started/requirements.html[Learn more^] about supported Astra Trident versions and other Astra Control Center requirements.

.Steps

. Determine if the original installation method used an https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html#determine-the-original-installation-method[operator (either manually or with Helm) or `tridentctl`^].
+
NOTE: If you used Helm for the original install and you are upgrading to 23.10, you'll need to use either the Trident operator or tridentctl to perform the upgrade.

. If you are upgrading to Astra Trident 23.10 and later, use one of these procedures to enable the Astra Control Provisioner for Astra Trident. The Astra Control Provisioner enables access to closed-source Astra Trident functionality that is available to all licensed Astra Control users beginning with Astra Trident 23.10.
+
[role="tabbed-block"]
====

.Astra Trident operator
--
. Delete the Trident operator that was used to install the current Astra Trident instance. For example, if you are upgrading from Astra Trident 23.07, run the following command:
+
----
kubectl delete -f 23.07/trident-installer/deploy/<bundle-name.yaml> -n trident
----

. Update the TridentOrchestrator CR to enable Astra Control Provisioner (`--enable-acp=true`):
+
----
./tridentctl -n trident install --debug --enable-acp=true --acp-image=mycustomregistry/trident-acp:v23.10
----

. Install Trident operator 23.10 or later:
+
NOTE: For clusters running Kubernetes 1.24 or earlier, use `bundle_pre_1_25.yaml`. For clusters running Kubernetes 1.25 or later, use `bundle_post_1_25.yaml`.
+
----
kubectl create -f deploy/<bundle-name>.yaml
----

. Verify the operator, deployment, and replicasets were created. 
+
----
kubectl get all -n <operator-namespace>
----
+
IMPORTANT: There should only be *one instance* of the operator in a Kubernetes cluster. Do not create multiple deployments of the Trident operator.

. Verify the trident-acp service has been installed:
+
----
GET <trident-address>/trident/v1/<object-type>/trident-acp
----
--

.tridentctl
--

. https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-tridentctl.html[Uninstall Astra Trident^].
. Update the TridentOrchestrator CR that is leftover from the uninstall process and enable Astra Control Provisioner (`--enable-acp=true`):
+
----
./tridentctl -n trident install --debug --enable-acp=true --acp-image=mycustomregistry/trident-acp:v23.10
----

. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-tridentctl.html[Install Astra Trident again^].
====
// end tabbed block

. If you are upgrading to Astra Trident 23.07 or an earlier supported version, refer to https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html[Astra Trident documentation^].

.For more information

* https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator-overview.html[Astra Trident upgrades documentation^]