---
sidebar: sidebar
permalink: use/upgrade-acc.html
keywords: astra upgrade, upgrade astra control center, how to upgrade astra control, update
summary: To upgrade Astra Control Center, you'll download the bundle and upgrade following the steps described.
---

= Upgrade Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To upgrade Astra Control Center, download the installation bundle from the NetApp Support Site and complete these instructions. You can use this procedure to upgrade Astra Control Center in internet-connected or air-gapped environments.

These instructions describe the upgrade process for Astra Control Center from the second-most recent release to this current release. You cannot upgrade directly from a version that is two or more releases behind the current release. If your installed Astra Control Center version is many versions behind the latest release, you might need to perform chain upgrades to more recent versions until your installed Astra Control Center is only one version behind the latest release. For a complete list of released versions, see the link:../release-notes/whats-new.html[release notes^].

.Before you begin
Before you upgrade, ensure your environment still meets the link:../get-started/requirements.html[minimum requirements for Astra Control Center deployment^]. Your environment should have the following:

* *A link:../get-started/requirements.html#astra-trident-requirements[supported] Astra Trident version*
+
.Expand for details
[%collapsible]
====
Determine the Trident version you are running:

[source,console]
----
kubectl get tridentversion -n trident
----

NOTE: Upgrade Astra Trident, if required, using these https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html[instructions^]. 

====
// End snippet

IMPORTANT: The 23.10 release is the last release of Astra Control Center that will support Astra Trident. It is strongly recommended that you link:../use/enable-acp.html[enable Astra Control Provisioner] to access advanced management and storage provisioning features beyond those that Astra Trident provides today. You must both upgrade to Astra Control Center 23.10 and enable Astra Control Provisioner to use this extended functionality. Astra Control Provisioner will not work with earlier releases of Astra Control Center. 

* *A supported Kubernetes distribution*
+
.Expand for details
[%collapsible]
====
Determine the Kubernetes version you are running:

[source,console]
----
kubectl get nodes -o wide
----
====
// End snippet

* *Sufficient cluster resources*
+
.Expand for details
[%collapsible]
====
Determine available cluster resources: 

[source,console]
----
kubectl describe node <node name>
----
====
// End snippet

* *A registry you can use to push and upload Astra Control Center images*
* *A default storage class*
+
.Expand for details
[%collapsible]
====
Determine your default storage class:

[source,console]
----
kubectl get storageclass
----
====
// End snippet

* *Healthy and available API services*
+
.Expand for details
[%collapsible]
====
Ensure all API services are in a healthy state and available:

[source,console]
----
kubectl get apiservices
----
====
// End snippet

* *(OpenShift only) Healthy and available cluster operators*
+
.Expand for details
[%collapsible]
====
Ensure all cluster operators are in a healthy state and available.

[source,console]
----
kubectl get clusteroperators
----
====
// End snippet

include::../_include/access-netapp-image-registry.adoc[]

//astradoc-249
//* Service mesh considerations: It is strongly recommended that Astra Control host cluster communications channels be secured using a link:../get-started/requirements.html#service-mesh-requirements[service mesh]. If you already have an existing Astra Control Center instance that is participating in Istio service mesh or you do not intend to install an Istio service mesh for use with Astra Control Center, _no additional service mesh changes are needed_ for upgrade configuration. If you intend to install and use an Istio service mesh, _the following steps are required_:
//+
//[id=istioprereq]
//.Istio service mesh prerequisite steps for Astra Control Center upgrades
//[%collapsible]
//====
//Before upgrading Astra Control Center, perform these steps:
//
//. Install the Istio service mesh on the host cluster. 
//+
//IMPORTANT: Don't attempt to add the mesh to the existing Astra installation. The Istio service mesh must be running in parallel with an existing, un-meshed Astra Control Center installation.
//
//. Add the following labels to the Astra (`netapp-acc` or custom namespace) namespace:
//+
//[source,console]
//----
//kubectl label ns [netapp-acc or custom namespace] istio-injection:disabled
//----
//+
//[source,console]
//----
//kubectl label ns [netapp-acc or custom namespace] astra.netapp.io/istio:on-upgrade
//----
//
//NOTE: When you perform the upgrade, you will also need to ensure that the `ingressType` you specify in link:../use/upgrade-acc.html#upgrade-astra-control-center[the Astra Control Center CR] is `Generic` and not `AccTraefik` or the upgrade will fail.
//
//====
// End snippet

.About this task
The Astra Control Center upgrade process guides you through the following high-level steps:

NOTE: Log out of your Astra Control Center UI before you begin the upgrade.

* <<Download and extract Astra Control Center>>
* <<Remove the NetApp Astra kubectl plugin and install it again>>
* <<Add the images to your local registry>>
* <<Install the updated Astra Control Center operator>>
* <<Upgrade Astra Control Center>>
* <<Verify system status>>

IMPORTANT: Do not delete the Astra Control Center operator (for example, `kubectl delete -f astra_control_center_operator_deploy.yaml`) at any time during the Astra Control Center upgrade or operation to avoid deleting pods.

TIP: Perform upgrades in a maintenance window when schedules, backups, and snapshots are not running.

include::../_include/download-extract-acc.adoc[]

== Remove the NetApp Astra kubectl plugin and install it again

You can use the NetApp Astra kubectl command line plugin to push images to a local Docker repository.

. Determine if you have the plug-in installed:
+
[source,console]
----
kubectl astra
----

. Take one of these actions:
** If the plugin is installed, the command should return the kubectl plugin help and you can remove the existing version of kubectl-astra: `delete /usr/local/bin/kubectl-astra`. 
** If the command returns an error, the plugin is not installed and you can proceed to the next step to install it.

. Install the plugin:
.. List the available NetApp Astra kubectl plugin binaries, and note the name of the file you need for your operating system and CPU architecture: 
+
NOTE: The kubectl plugin library is part of the tar bundle and is extracted into the folder `kubectl-astra`.
+
[source,console]
----
ls kubectl-astra/
----
.. Move the correct binary into the current path and rename it to `kubectl-astra`:
+
[source,console]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----

include::../_include/docker-podman-add-images.adoc[]

== Install the updated Astra Control Center operator

. Change the directory:
+
[source,console]
----
cd manifests
----

. Edit the Astra Control Center operator deployment yaml (`astra_control_center_operator_deploy.yaml`) to refer to your local registry and secret.
+
[source,console]
----
vim astra_control_center_operator_deploy.yaml
----

.. If you use a registry that requires authentication, replace or edit the default line of `imagePullSecrets: []` with the following:
+
[source,console]
----
imagePullSecrets: [{name: astra-registry-cred}]
----

.. Change `ASTRA_IMAGE_REGISTRY` for the `kube-rbac-proxy` image to the registry path where you pushed the images in a <<Add the images to your local registry,previous step>>.
.. Change `ASTRA_IMAGE_REGISTRY` for the `acc-operator` image to the registry path where you pushed the images in a <<Add the images to your local registry,previous step>>.
//DOC-4167/ASTRACTL-16917/PI5
.. Add the following values to the `env` section:
+
[source,console]
----
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
----

+
.Sample astra_control_center_operator_deploy.yaml:
[%collapsible]
====

[subs=+quotes]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: ASTRA_IMAGE_REGISTRY/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *- name: ACCOP_HELM_UPGRADETIMEOUT*
          *value: 300m*
        *image: ASTRA_IMAGE_REGISTRY/acc-operator:23.07.25*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----
====
// End snippet

. Install the updated Astra Control Center operator:
+
[source,console]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
.Sample response:
[%collapsible]
====
----
namespace/netapp-acc-operator unchanged
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io configured
role.rbac.authorization.k8s.io/acc-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding unchanged
configmap/acc-operator-manager-config unchanged
service/acc-operator-controller-manager-metrics-service unchanged
deployment.apps/acc-operator-controller-manager configured
----
====
// End snippet

. Verify pods are running:
+
[source,console]
----
kubectl get pods -n netapp-acc-operator
----

== Upgrade Astra Control Center

. Edit the Astra Control Center custom resource (CR):
+
[source,console]
----
kubectl edit AstraControlCenter -n [netapp-acc or custom namespace]
----

. Change the Astra version number (`astraVersion` inside of `spec`) to the version you are upgrading to:
+
[subs=+quotes]
----
spec:
  accountName: "Example"
  *astraVersion: "[Version number]"*
----

. Verify that your image registry path matches the registry path you pushed the images to in a <<Add the images to your local registry,previous step>>. Update `imageRegistry` inside of `spec` if the registry has changed since your last installation.
+
----
  imageRegistry:
    name: "[your_registry_path]"
----

. Add the following to your `crds` configuration inside of `spec`:
+
[source,console]
----
crds:
  shouldUpgrade: true
----

. Add the following lines within `additionalValues` inside of `spec` in the Astra Control Center CR:
+
[source,console]
----
additionalValues:
    nautilus:
      startupProbe:
        periodSeconds: 30
        failureThreshold: 600
    polaris-keycloak:
      livenessProbe:
        initialDelaySeconds: 180
      readinessProbe:  
        initialDelaySeconds: 180
----
//astradoc-245/known issue/23.07 only
//
//astradoc-249
//. If you installed a new Istio service mesh on the host cluster according to the <<istioprereq,prerequisite steps>> described earlier in this procedure, change the ingress setting to `Generic`:
//+
//[source,console]
//----
//ingressType: Generic
//----
//
. Save and exit the file editor. The changes will be applied and the upgrade will begin.

. (Optional) Verify that the pods terminate and become available again:
+
[source,console]
----
watch kubectl get pods -n [netapp-acc or custom namespace]
----

. Wait for the Astra Control status conditions to indicate that the upgrade is complete and ready (`True`):
+
[source,console]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
Response:
+
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f      23.07.0-25   10.111.111.111  True
----
+
NOTE: To monitor upgrade status during the operation, run the following command: `kubectl get AstraControlCenter -o yaml -n [netapp-acc or custom namespace]`

+
NOTE: To inspect the Astra Control Center operator logs, run the following command:
`kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f`

== Verify system status

. Log in to Astra Control Center.
. Verify that the version has been upgraded. See the *Support* page in the UI.
. Verify that all your managed clusters and apps are still present and protected.

