---
sidebar: sidebar
permalink: use/view-dashboard.html
keywords: dashboard, cluster health, unhealthy apps, protected apps, discovered apps
summary: Select Dashboard to see a high-level view of your apps, compute, and their health.
---

= View a summary of app and cluster health
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Select the *Dashboard* to see a high-level view of your apps, clusters, storage backends, and their health.

These aren't just static numbers or statuses--you can drill down from each. For example, if apps aren't fully protected, you can hover over the icon to identify which apps aren't fully protected, which includes a reason why.

== Applications tile
The *Applications* tile helps you identify the following:

* How many apps you're currently managing with Astra.
* Whether those managed apps are healthy.
* Whether the apps are fully protected (they're protected if recent backups are available).
* The number of apps that were discovered, but are not yet managed.
+
Ideally, this number would be zero because you would either manage or ignore apps after they're discovered. And then you would monitor the number of discovered apps on the Dashboard to identify when developers add new apps to a cluster.


== Clusters tile
The *Clusters* tile provides similar details about the health of the clusters that you are managing by using Astra Control Center, and you can drill down to get more details just like you can with an app.

== Storage backends tile

The *Storage backends* tile provides information to help you identify the health of storage backends including:

* How many storage backends are managed
* Whether these managed backends are healthy
* Whether the backends are fully protected
* The number of backends that are discovered, but are not yet managed.
