---
sidebar: sidebar
permalink: use/view-clusters.html
keywords: view cluster, cluster storage, cluster overview
summary: After you add clusters to Astra Control Center, you can view details about the cluster, such as its location, the worker nodes, persistent volumes, and storage classes.
---

= View the health and details of clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
After you add clusters to be managed by Astra Control Center, you can view details about the cluster, such as its location, the worker nodes, persistent volumes, and storage classes.

.Steps

. In the Astra Control Center UI, select *Clusters*.

. On the *Clusters* page, select the cluster whose details you want to view.

. View the information on the *Overview*, *Storage*, and *Activity* tabs to find the information that you're looking for.
+
* *Overview*: Details about the worker nodes, including their state.
* *Storage*: The persistent volumes associated with the compute, including the storage class and state.
* *Activity*: Shows the activities related to the cluster.

NOTE: You can also view cluster information starting from the Astra Control Center *Dashboard*. On the *Clusters* tab under *Resource summary*, you can select the managed clusters, which takes you to the *Clusters* page. After you get to the *Clusters* page, follow the steps outlined above.
