---
sidebar: sidebar
permalink: use/view-account-activity.html
keywords: activity, log, activities, download log, download csv, csv
summary: You can view details about the activities in your Astra Control account. For example, when new users were invited, when a cluster was added, or when a snapshot was taken. You also have the ability to export your account activity to a CSV file.
---

= Monitor account activity
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
//IE NOTE: Nearly identical to comparable ACS topic. Make AC edits in both.
You can view details about the activities in your Astra Control account. For example, when new users were invited, when a cluster was added, or when a snapshot was taken. You also have the ability to export your account activity to a CSV file.

TIP: If you manage Kubernetes clusters from Astra Control and Astra Control is connected to Cloud Insights, Astra Control sends event logs to Cloud Insights. The log information, including information about pod deployment and PVC attachments, appears in the Astra Control Activity log. Use this information to identify any issues on the Kubernetes clusters you are managing. 


.View all account activity in Astra Control

. Select *Activity*.

. Use the filters to narrow down the list of activities or use the search box to find exactly what you're looking for.

. Select *Export to CSV* to download your account activity to a CSV file.

.View account activity for a specific app

. Select *Applications* and then select the name of an app.

. Select *Activity*.

.View account activity for clusters

. Select *Clusters* and then select the name of the cluster.

. Select *Activity*.

.Take action to resolve events that require attention

. Select *Activity*.

. Select an event that requires attention.

. Select the *Take action* drop-down option.
+
From this list, you can view possible corrective actions that you can take, view documentation related to the issue, and get support to help resolve the issue.
