---
sidebar: sidebar
permalink: get-started/acc_operatorhub_install.html
keywords: astra installation, operator, operatorhub, install astra control center operator, how to install astra control center
summary: You can install the Astra Control Center operator from Operatorhub.io after addressing systems prerequisites and other installation steps.
---

= Install Astra Control Center operator from Operatorhub.io
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can install the Astra Control Center operator from https://operatorhub.io/[Operatorhub.io^] using the Red Hat Container Platform. You can also install the Astra Control Center through the same platform using this procedure.

After you complete this procedure, you must return to the installation procedure to complete the link:../get-started/install_acc.html#verify-system-status[remaining steps] to verify installation success and log on.

.What you'll need
* You have completed all steps including prerequisite steps from the link:../get-started/install_acc.html[installation procedure] prior to the step link:../get-started/install_acc.html#install-the-astra-control-center-operator[Install the Astra Control Center operator].
* You have created an FQDN address for Astra Control Center in your data center.
* You have the necessary permissions and access to the Red Hat OpenShift Container Platform to perform the steps described.

.Steps

* <<Find the operator install page>>
* <<Install the operator>>
* <<Install Astra Control Center>>

== Find the operator install page

. From the Red Hat OpenShift console, go to the Operatorhub menu and https://operatorhub.io/?keyword=netapp[select^] the NetApp Astra Control Center operator.
. Select *Install*.

== Install the operator

. Complete the *Install Operator* page and install the operator:
+
NOTE: The operator will be available in all cluster namespaces.

.. Select the operator namespace or `netapp-acc-operator` namespace will be created automatically as part of the operator installation.
.. Select a manual or automatic approval strategy.
.. Select *Install*.
.. If you select a manual approval strategy, you will prompted to approve the manual install plan for this operator.
. From the console, go to the Operatorhub menu and confirm that the operator installed successfully.

== Install Astra Control Center

. From the console within the details view of the Astra Control Center operator, select `Create instance` in the Provided APIs section.
. Complete the `Create AstraControlCenter` form field:
.. Keep or adjust the Astra Control Center name.
.. Retain the Auto Support value.
+
NOTE: Auto support is required for Astra Data Store preview.

.. Enter the Astra Control Center address. Do not use `http://` or `https://` in the address.
.. Enter the Astra Control Center version you are deploying.
.. Enter an account name, email address, and admin last name.
.. Retain the default volume reclaim policy.
.. In *Image Registry*, enter your local container image registry path. Do not use `http://` or `https://` in the address.
.. If you use a registry that requires authentication, enter the secret.
.. Enter the admin first name.
.. Configure resources scaling.
.. Retain the default storage class.
.. Define CRD handling preferences.
.. Select `Create`.

== What's next

Complete installation by verifying the successful of Astra Control Center and completing the link:../get-started/install_acc.html#verify-system-status[remaining steps] to log on.

NOTE: You can alternatively verify successful installation of the Astra Control Center from the `AstraControlCenter details` tab within your installed operator in the Red Hat console.
