---
sidebar: sidebar
permalink: get-started/acc_operatorhub_install.html
keywords: astra installation, operator, operatorhub, install astra control center operator, how to install astra control
summary: You can install the Astra Control Center operator from Operatorhub.io after addressing systems prerequisites and other installation steps.
---

= Install Astra Control Center operator from Operatorhub.io
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can install the Astra Control Center operator from https://operatorhub.io/[Operatorhub.io]. After you complete this procedure, you must return to the installation procedure to complete the link:../get-started/install_acc.html#configure-astra-control-center[remaining steps].

.What you'll need
* You have completed all steps including prerequisite steps from the link:../get-started/install_acc.html[installation procedure] prior to the step link:../get-started/install_acc.html#configure-the-astra-control-center-operator[Configure the Astra Control Center operator].

.Steps

. https://operatorhub.io/?keyword=netapp[Select] the NetApp Astra Control Center operator.
. Confirm that you have completed any system prerequisites described in the summary documentation.
. Configure the Astra Control Center operator deployment YAML (`astra_control_center_operator_deploy.yaml`) using the form field to refer to your local registry and secret:
.. If you use a registry that requires authentication, replace the default line of `imagePullSecrets: []` with the following:
+
----
imagePullSecrets:
- name: astra-registry-cred
----

.. Change `[your_registry_path]` for the `kube-rbac-proxy` image to the registry path where you pushed the images in a <<substep_image_local_registry_push,previous step>>.
.. Change `[your_registry_path]` for the `acc-operator-controller-manager` image to the registry path where you pushed the images in a <<substep_image_local_registry_push,previous step>>.

+
[subs=+quotes]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----

. Click *Install* to apply the operator YAML.
+
Sample response:
+
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----

== What's next

Complete Astra Control Center installation by completing the link:../get-started/install_acc.html#configure-astra-control-center[remaining steps].
