---
sidebar: sidebar
permalink: get-started/add-first-cluster.html
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add compute
summary: After you set up your environment, you're ready to create a Kubernetes cluster and then add it to Astra.
---

= Start managing Kubernetes compute from Astra
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
After you set up your environment, you're ready to create a Kubernetes cluster and then add it to Astra.

== Create a Kubernetes cluster

If you don't have a cluster yet, create a cluster in Kubernetes link:../learn/requirements.html[that meets Astra requirements].

== Start managing Kubernetes compute

After you log in to Astra, your first step is to start managing compute.

.Steps

. On the Dashboard, click *Manage Kubernetes compute*.
+
Follow the prompts to add the compute.

. *Provider*: For Astra Enterprise, select *Private Cloud*.

. Select *Discover Compute*.
. Select *Configure Compute*.
. Select *Add Compute* to add on-premise compute.
. Select the *Storage* tab, which you use to specify the compute cluster for Astra Enterprise. This page shows ONTAP as the storage backend.
. Review the basic information about the Kubernetes compute cluster in the charts. The data is an excerpt from Cloud Insights.
. Select the compute that you'd like to add.
+
Pay careful attention to the Eligible tab. If a warning appears, hover over the warning to determine if there's an issue with the compute. For example, it might identify that the cluster doesn't have a worker node.
. Select the default storage class that you'd like to use with this compute.
+
link:../learn/choose-class-and-size.html[Learn about choosing a storage class].

. *Review & Approve*: Review the configuration details and click *Add compute*.

The following video shows each of these steps.

video::video-manage-cluster.mp4[width=848, height=480]

.Result

Astra creates an object store for application backups, creates an admin account on the cluster, and sets the default storage class that you specified. This process can take up to 5 minutes.
