---
sidebar: sidebar
permalink: get-started/configure-after-install.html
keywords: configure, installation, install, after, Astra Control Center, 
summary: Depending on your environment, there might be some configuration needed after you install Astra Control Center.
---

= Configure Astra Control Center after installation
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Depending on your environment, there might be further configuration needed after you install Astra Control Center.

== Remove resource limitations
Some environments use the ResourceQuotas and LimitRanges objects to prevent the resources in a namespace from consuming all available CPU and memory on the cluster. Astra Control Center does not set maximum limits, so it will not be in compliance with those resources. You need to remove them from the namespaces where you plan to install Astra Control Center.

You can use the following steps to retrieve and remove these quotas and limits. In these examples, the command output is shown immediately after the command.

.Steps

. Get the resource quotas in the netapp-acc namespace:
+
[source,sh]
----
kubectl get quota -n netapp-acc
----
+
Response:
+
----
NAME          AGE   REQUEST                                        LIMIT
pods-high     16s   requests.cpu: 0/20, requests.memory: 0/100Gi   limits.cpu: 0/200, limits.memory: 0/1000Gi
pods-low      15s   requests.cpu: 0/1, requests.memory: 0/1Gi      limits.cpu: 0/2, limits.memory: 0/2Gi
pods-medium   16s   requests.cpu: 0/10, requests.memory: 0/20Gi    limits.cpu: 0/20, limits.memory: 0/200Gi
----
. Delete all of the resource quotas by name:
+
[source,sh]
----
kubectl delete resourcequota  pods-high -n netapp-acc
----
+
[source,sh]
----
kubectl delete resourcequota  pods-low -n netapp-acc
----
+
[source,sh]
----
kubectl delete resourcequota  pods-medium -n netapp-acc
----

. Get the limit ranges in the netapp-acc namespace:
+
[source,sh]
----
kubectl get limits -n netapp-acc
----
+
Response:
+
----
NAME              CREATED AT
cpu-limit-range   2022-06-27T19:01:23Z
----

. Delete the limit ranges by name:
+
[source,sh]
----
kubectl delete limitrange cpu-limit-range -n netapp-acc
----

== Enable network communication between namespaces
Some environments use NetworkPolicy constructs to restrict traffic between namespaces. The Astra Control Center operator and Astra Control Center are in different namespaces. The services in these different namespaces need to be able to communicate with one another. To enable this communication, follow these steps.

.Steps

. Delete any NetworkPolicy resources that exist in the Astra Control Center namespace:
+
[source,sh]
----
kubectl get networkpolicy -n netapp-acc
----
. For each NetworkPolicy object that is returned by the preceding command, use the following command to delete it. Replace <OBJECT_NAME> with the name of the returned object:
+
[source,sh]
----
kubectl delete networkpolicy <OBJECT_NAME> -n netapp-acc
----

. Apply the following resource file to configure the acc-avp-network-policy object to allow  Astra plugin services to make requests to Astra Control Center services. Replace the information in brackets <> with information from your environment:
+
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: acc-avp-network-policy
  namespace: <ACC_NAMESPACE_NAME> # REPLACE THIS WITH THE ASTRA CONTROL CENTER NAMESPACE NAME
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: <PLUGIN_NAMESPACE_NAME> # REPLACE THIS WITH THE ASTRA PLUGIN NAMESPACE NAME
----

. Apply the following resource file to configure the acc-operator-network-policy object to allow the Astra Control Center operator to communicate with Astra Control Center services. Replace the information in brackets <> with information from your environment:
+
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: acc-operator-network-policy
  namespace: <ACC_NAMESPACE_NAME> # REPLACE THIS WITH THE ASTRA CONTROL CENTER NAMESPACE NAME
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: <NETAPP-ACC-OPERATOR> # REPLACE THIS WITH THE OPERATOR NAMESPACE NAME
----
