---
sidebar: sidebar
permalink: get-started/faq.html
keywords: faq, frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for Astra Enterprise
:hardbreaks:
:icons: font
:imagesdir: ../media/

This FAQ can help if you're just looking for a quick answer to a question.

== Overview

Astra aims to simplify your application data lifecycle management operations for Kubernetes native applications. Astra supports Kubernetes clusters running in the cloud and on-premise.

The following sections provide answers to some additional questions that you might come across as you use Astra Enterprise. For additional clarifications, please reach out to astra.feedback@netapp.com

== Access to Astra


*What's the Astra Enterprise URL?*

You can access Astra at https://astra.netapp.io.

*I set up email notifications and tested an email to a colleague, but it hasn't been received. What should I do?*

Ask them to check their spam folder for an email from do-not-reply@netapp.com, or search their inbox for "astra." You can also remove the user and attempt to re-add them.

*I am using the Trial license. How to I change to the full license?*

ANSWER TBD.

*I am using the Trial license. Can I still use the Persistent Volume Claim functionality in Trident?*

Yes, you can test out the Persistent Volumes functionality with the Trial license.  (TRUE???)

== Registering Kubernetes clusters

*Can I add a private cluster to Astra?*

Yes, you can add private clusters to Astra. To create private cluster, https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Project_Astra/How_to_create_a_private_GKE_cluster_to_work_with_project_Astra[follow the instructions in this knowledgebase article^].

Private clusters must have the https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[master authorized network^] set to allow the Astra IP addresses:

* 54.164.233.140/32
* 3.218.120.204/32
* 34.193.99.138/32

*Can my cluster reside on a shared VPC?*

No, Astra can’t manage clusters that reside in a shared VPC. This is a known limitation.


*I would like to add different clusters from different projects. Is this supported in Astra?*

No, this isn't a supported configuration. Only a single project is supported. (TRUE??? )

*I need to add worker nodes to my Kubernetes cluster after adding to Astra. What should I do?*

New worker nodes can be added to existing pools, or new pools can be created as long as they are the Ubuntu image type. These will be automatically discovered by Astra. If the new nodes are not visible in Astra, check if the new worker nodes are running the supported image type. You can also verify the health of the new worker nodes by using the `kubectl get nodes` command.

*How do I properly unregister, bring down a cluster, and delete the associated volumes?*

.	link:../use/unmanage.html[Unmanage the applications from Astra].
.	link:../use/unmanage.html#stop-managing-compute[Unregister the cluster from Astra].
.	Delete the application namespace from the Kubernetes cluster.
+
Alternatively, delete the PVCs and PVs. This will remove the volume from Cloud Volumes Service.
.	Delete the cluster.

NOTE: If you forget step 3, or if you used a storage class with the reclaim policy set to _retain_, the volume will remain in Cloud Volumes Service indefinitely. If this happens and you want to delete the volume, then you'll need to delete the volume manually.

*What happens to my applications and data after removing the Kubernetes cluster from Astra?*

Removing a cluster from Astra will not make any changes to the cluster's configuration (applications and persistent storage). Any Astra snapshots or backups taken of applications on that cluster will be unavailable to restore. Persistent Storage backups created by Astra will remain within Astra Enterprise, but they are unavailable for restore.

WARNING: Always remove a cluster from Astra before you delete it through any other methods. Deleting a cluster using another tool while it's still being managed by Astra can cause problems for your Astra account.

*Will NetApp Trident be uninstalled when I remove a Kubernetes cluster from Astra?*

Trident will not be uninstalled from a cluster when you remove it from Astra.

== Managing applications

*My application is not showing up on the Discovered Apps list. What can I check to identify the problem?*

When applications are not listed in *Discovered Apps*, check the status and health of the Kubernetes pod by running `kubectl get pod -A |grep [pod name]`. If the pods are healthy and running, check to see if the application is listed under *Ignored Apps*.

*I don’t see any of my application’s PVCs bound to XYZ. What's wrong?*

The NetApp Trident operator sets the default storage class to `netapp-cvs-premium` after it's successfully added to Astra. When an application's PVCs are not bound to XYZ, there are a few steps that you can take:

* Run `kubectl get sc` and check the default storage class.
* Check the yaml file or Helm chart that was used to deploy the application and see if a different storage class is defined.
* Check to make sure that the worker node image type is Ubuntu and the NFS mount succeeded.

*Can Astra deploy an application?*

Astra doesn't deploy applications. Applications must be deployed outside of Astra.

*What happens to applications after I stop managing them from Astra?*

Any existing backups or snapshots will be deleted. Applications and data remain available. Data management operations will not be available for unmanaged applications or any backups or snapshots that belong to it.

*Can Astra manage an application that is on non-NetApp storage?*

No. While Astra can discover applications that are using non-NetApp storage, it can't manage an application that's using non-NetApp storage.

== Data management operations

*Where is my object bucket created?*

The geography of the first managed cluster will determine the location of the object store. For example, if you add a cluster in a European zone, then remove that cluster and add one in the US, all future object stores will be created in EU. If you need to change this zone, please contact our support department.

*There are snapshots in my account that I didn't create. Where did they come from?*

In some situations, Astra will automatically create a snapshot as part of performing another process. If these snapshots are more than a few minutes old, you can safely delete them.

*My application uses several PVs. Will Astra take snapshots and backups of all these PVCs?*

Yes. A snapshot operation on an application by Astra includes snapshot of all the PVs that are bound to the application’s PVCs.

*Can I manage snapshots taken by Astra directly through a different interface or object storage?*

No. Snapshots and backups taken by Astra can only be managed with Astra.
