---
sidebar: sidebar
permalink: get-started/faq.html
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/

This FAQ can help if you're just looking for a quick answer to a question.

== Overview

The following sections provide answers to some additional questions that you might come across as you use Astra Control Center. For additional clarifications, please reach out to astra.feedback@netapp.com

== Access to Astra Control Center


*What's the Astra Control URL?*

Astra Control Center uses local authentication and a URL specific to each environment.

For the URL, in a browser, enter the Fully Qualified Domain Name (FQDN) you set in the spec.astraAddress field in the astra_control_center_min.yaml custom resource definition (CRD) file when you installed Astra Control Center. The email is the value that you set in the spec.email field in the astra_control_center_min.yaml CRD.

*I am using the Evaluation license. How to I change to the full license?*

You can easily change to a full license by obtaining the NetApp license file (NLF).

*Steps*

* From the left navigation, select *Account* > *License*.
* Select *Add license*.
* Browse to the license file you downloaded and select *Add*.

*I am using the Evaluation license. Can I still manage apps?*

Yes, you can test out the managing apps functionality with the Evaluation license.

== Registering Kubernetes clusters

*I need to add worker nodes to my Kubernetes cluster after adding to Astra Control. What should I do?*

New worker nodes can be added to existing pools. These will be automatically discovered by Astra Control. If the new nodes are not visible in Astra Control, check if the new worker nodes are running the supported image type. You can also verify the health of the new worker nodes by using the `kubectl get nodes` command.

*How do I properly unmanage a cluster?*

.	link:../use/unmanage.html[Unmanage the applications from Astra Control].
.	link:../use/unmanage.html#stop-managing-compute[Unmanage the cluster from Astra Control].


*What happens to my applications and data after removing the Kubernetes cluster from Astra Control?*

Removing a cluster from Astra Control will not make any changes to the cluster's configuration (applications and persistent storage). Any Astra Control snapshots or backups taken of applications on that cluster will be unavailable to restore. Persistent storage backups created by Astra Control remain within Astra Control, but they are unavailable for restore.

WARNING: Always remove a cluster from Astra Control before you delete it through any other methods. Deleting a cluster using another tool while it's still being managed by Astra Control can cause problems for your Astra Control account.

*Will NetApp Trident be uninstalled when I remove a Kubernetes cluster from Astra Control?*

Trident will not be uninstalled from a cluster when you remove it from Astra Control.

== Managing applications


*Can Astra Control deploy an application?*

Astra Control doesn't deploy applications. Applications must be deployed outside of Astra Control.

*What happens to applications after I stop managing them from Astra Control?*

Any existing backups or snapshots will be deleted. Applications and data remain available. Data management operations will not be available for unmanaged applications or any backups or snapshots that belong to it.

*Can Astra Control manage an application that is on non-NetApp storage?*

No. While Astra Control can discover applications that are using non-NetApp storage, it can't manage an application that's using non-NetApp storage.

*Should I manage Astra Control itself?*
No, you should not manage Astra Control itself because it is a "system app."

== Data management operations

*There are snapshots in my account that I didn't create. Where did they come from?*

In some situations, Astra Control will automatically create a snapshot as part of a backup, clone or restore process.

*My application uses several PVs. Will Astra Control take snapshots and backups of all these PVCs?*

Yes. A snapshot operation on an application by Astra Control includes snapshot of all the PVs that are bound to the application’s PVCs.

*Can I manage snapshots taken by Astra Control directly through a different interface or object storage?*

No. Snapshots and backups taken by Astra Control can only be managed with Astra Control.
