---
sidebar: sidebar
permalink: get-started/install_acc.html
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support
summary: To install Astra Control Center after addressing some environmental prerequisites, you'll download the bundle and install following the steps described.
---

= Install Astra Control Center using the standard process
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To install Astra Control Center, download the installation bundle from the NetApp Support Site and perform the following steps. You can use this procedure to install Astra Control Center in internet-connected or air-gapped environments.

.Other installation procedures
[%collapsible]
====
* *Install with RedHat Openshift OperatorHub*: Use this link:../get-started/acc_operatorhub_install.html[alternative procedure] to install Astra Control Center on Openshift using OperatorHub.
* *Install in the public cloud with Cloud Volumes ONTAP backend*: Use link:../get-started/install_acc-cvo.html[these procedures] to install Astra Control Center in Amazon Web Services (AWS), Google Cloud Platform (GCP), or Microsoft Azure with a Cloud Volumes ONTAP storage backend.
====
// End snippet

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Control Center deployment].
* If you have configured or want to configure pod security policies in your environment, familiarize yourself with pod security policies and how they affect Astra Control Center installation. See link:../concepts/understand-pod-security.html[Understand pod security policy restrictions].
* Ensure all API services are in a healthy state and available:
+
[source,console]
----
kubectl get apiservices
----

* Ensure the Astra FQDN you plan to use is routable to this cluster. This means that you either have a DNS entry in your internal DNS server or you are using a core URL route that is already registered.
* If a cert-manager already exists in the cluster, you need to perform some link:../get-started/cert-manager-prereqs.html[prerequisite steps] so that Astra Control Center does not attempt to install its own cert-manager. By default, Astra Control Center installs its own cert-manager during installation.

.About this task
The Astra Control Center installation process helps you to do the following:

* Install the Astra components into the `netapp-acc` (or custom-named) namespace.
* Create a default Astra Control Owner admin account.
* Establish an administrative user email address and default initial setup password. This user is assigned the Owner role that is needed for first time login to the UI.
* Determine that all Astra Control Center pods are running.
* Install the Astra Control Center UI.
//VMware ADS EAP review


IMPORTANT: Do not delete the Astra Control Center operator (for example, `kubectl delete -f astra_control_center_operator_deploy.yaml`) at any time during Astra Control Center installation or operation to avoid deleting pods.

.Steps

To install Astra Control Center, do the following steps:

* <<Download and extract Astra Control Center>>
* <<Install the NetApp Astra kubectl plugin>>
* <<Add the images to your local registry>>
* <<Set up namespace and secret for registries with auth requirements>>
* <<Install the Astra Control Center operator>>
* <<Configure Astra Control Center>>
* <<Complete Astra Control Center and operator installation>>
* <<Verify system status>>
* <<Set up ingress for load balancing>>
* <<Log in to the Astra Control Center UI>>

include::../_include/download-extract-acc.adoc[]

== Install the NetApp Astra kubectl plugin

The NetApp Astra kubectl command line plugin saves time when performing common tasks associated with deploying and upgrading Astra Control Center.

.What you'll need

NetApp provides plugin binaries for different CPU architectures and operating systems. You need to know which CPU and operating system you have before you perform this task.

.Steps

. List the available NetApp Astra kubectl plugin binaries, and note the name of the file you need for your operating system and CPU architecture: 
+
NOTE: The kubectl plugin library is part of the tar bundle and is extracted into the folder `kubectl-astra`.
+
[source,console]
----
ls kubectl-astra/
----
. Move the correct binary into the current path and rename it to `kubectl-astra`:
+
[source,console]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----

include::../_include/docker-podman-add-images.adoc[]

== Set up namespace and secret for registries with auth requirements

. Export the KUBECONFIG for the Astra Control Center host cluster:
+
[source,console]
----
export KUBECONFIG=[file path]
----
+
NOTE: Before you complete the installation, be sure your KUBECONFIG is pointing to the cluster where you want to install Astra Control Center. The KUBECONFIG can contain only one context.


.  If you use a registry that requires authentication, you need to do the following:
.. Create the `netapp-acc-operator` namespace:
+
[source,console]
----
kubectl create ns netapp-acc-operator
----
+
Response:
+
----
namespace/netapp-acc-operator created
----

.. Create a secret for the `netapp-acc-operator` namespace. Add Docker information and run the following command:
+
NOTE: The placeholder `your_registry_path` should match the location of the images that you uploaded earlier (for example, `[Registry_URL]/netapp/astra/astracc/22.11.0-82`).
+
[source,console]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Sample response:
+
----
secret/astra-registry-cred created
----
+
NOTE: If you delete the namespace after the secret is generated, recreate the namespace and then regenerate the secret for the namespace.

.. Create the `netapp-acc` (or custom-named) namespace.
+
[source,console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
Sample response:
+
----
namespace/netapp-acc created
----

.. Create a secret for the `netapp-acc` (or custom-named) namespace. Add Docker information and run the following command:
+
[source,console]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Response
+
----
secret/astra-registry-cred created
----

== Install the Astra Control Center operator

. Change the directory:
+
[source,console]
----
cd manifests
----

. Edit the Astra Control Center operator deployment YAML (`astra_control_center_operator_deploy.yaml`) to refer to your local registry and secret.
+
[source,console]
----
vim astra_control_center_operator_deploy.yaml
----
+
NOTE: An annotated sample YAML follows these steps.

.. If you use a registry that requires authentication, replace the default line of `imagePullSecrets: []` with the following:
+
[source,console]
----
imagePullSecrets:
- name: astra-registry-cred
----

.. Change `[your_registry_path]` for the `kube-rbac-proxy` image to the registry path where you pushed the images in a <<Add the images to your local registry,previous step>>.
.. Change `[your_registry_path]` for the `acc-operator-controller-manager` image to the registry path where you pushed the images in a <<Add the images to your local registry,previous step>>.
+
[source]
[subs="specialcharacters,quotes"]
----
*astra_control_center_operator_deploy.yaml*
----
+
[subs=+quotes]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        - name: ACCOP_HELM_INSTALLTIMEOUT
          value: 5m
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----

. Install the Astra Control Center operator:
+
[source,console]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Sample response:
+
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----

. Verify pods are running:
+
[source,console]
----
kubectl get pods -n netapp-acc-operator
----

== Configure Astra Control Center

. Edit the Astra Control Center custom resource (CR) file (`astra_control_center.yaml`) to make account, AutoSupport, registry, and other necessary configurations:
+
[source,console]
----
vim astra_control_center.yaml
----
+
NOTE: An annotated sample YAML follows these steps.

.. Modify the following required settings:
+
.accountName
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example


| accountName
| Required
| Change the `accountName` string to the name you want to associate with the Astra Control Center account. There can be only one accountName.
| string
| Example

|===
====
// End snippet
+
.astraAddress
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| astraAddress
| Required
| Change the `astraAddress` string to the FQDN (recommended) or IP address you want to use in your browser to access Astra Control Center. This address defines how Astra Control Center will be found in your data center and is the same FQDN or IP address you provisioned from your load balancer when you completed link:requirements.html[Astra Control Center requirements].

NOTE: Do not use `http://` or `https://` in the address. Copy this FQDN for use in a <<Log in to the Astra Control Center UI,later step>>.
| string
| astra.example.com

|===
====
// End snippet
+
.autoSupport
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| autoSupport
| Required
| Your selections in this section determine whether you will participate in NetApp's pro-active support application, NetApp Active IQ., and where data is sent. An internet connection is required (port 442), and all support data is anonymized.
| Undefined
|

| autoSupport.enrolled
| Optional, but either `enrolled` or `url` fields must be selected
| Change `enrolled` for AutoSupport to `false` for sites without internet connectivity or retain `true` for connected sites. A setting of `true` enables  anonymous data to be sent to NetApp for support purposes. The default election is `false` and indicates no support data will be sent to NetApp.
| Boolean
| false (this value is the default)

| autoSupport.url
| Optional, but either `enrolled` or `url` fields must be selected
| This URL determines where the anonymous data will be sent.
| string
| https://support.netapp.com/asupprod/post/1.0/postAsup

|===
====
// End snippet
+
.email
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| email
| Required
| Change the `email` string to the default initial administrator address. Copy this email address for use in a <<Log in to the Astra Control Center UI,later step>>. This email address will be used as the username for the initial account to log in to the UI and will be notified of events in Astra Control.
| string
| admin@example.com

|===
====
// End snippet
+
.(Optional) firstName and LastName
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| firstName
| Required
| The first name of the default initial administrator associated with the Astra account. The name used here will be visible in a heading in the UI after your first login.
| string
| SRE

| lastName
| Required
| The last name of the default initial administrator associated with the Astra account. The name used here will be visible in a heading in the UI after your first login.
| string
| Admin

|===
====
// End snippet
+
.imageRegistry
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| imageRegistry
| Optional
| Your selections in this section define container image registry that is hosting the Astra application images, Astra Control Center Operator, and Astra Control Center Helm Repository.
| Undefined
|

| imageRegistry.name
| Required if you are using imageRegistry
| The name of the image registry where you pushed the images in the <<Install the Astra Control Center operator,previous step>>. Do not use `http://` or `https://` in the registry name.
| string
| example.registry.com/astra

| imageRegistry.secret
| Required if you are using imageRegistry that requires a secret
| The name of the Kubernetes secret used to authenticate with the image registry.

IMPORTANT: If you are using a registry that does not require authorization, you must delete this `secret` line within `imageRegistry` or the installation will fail.
| string
| astra-registry-cred

|===
====
// End snippet
+
.(Optional) storageClass
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| storageClass
| Optional (this is the default value)
| Change the `storageClass` value from the default value of 'ontap-gold' to another Trident storageClass resource as required by your installation. Run the command `kubectl get sc` to determine your existing configured storage classes. This is the storage class that will be used for PVCs. If it is not set, the default storage class will be used.
| string
| ontap-gold

|===
====
// End snippet
+
.ingressType
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| ingressType
| Optional
| Use one of the following ingress types:
+
* *Generic* (`ingressType: "Generic"`) (Default)
+
Use this option when you have another ingress controller in use or would prefer to use your own ingress controller. After Astra Control Center is deployed, you will need to configure the link:../get-started/install_acc.html#set-up-ingress-for-load-balancing[ingress controller] to expose Astra Control Center with a URL.

* *AccTraefik* (`ingressType: "AccTraefik"`)
+
Use this option when you would prefer not to configure an ingress controller. This deploys the Astra Control Center `traefik` gateway as a Kubernetes LoadBalancer type service.
+
Astra Control Center uses a service of the type "LoadBalancer" (`svc/traefik` in the Astra Control Center namespace), and requires that it be assigned an accessible external IP address. If load balancers are permitted in your environment and you don't already have one configured, you can use MetalLB or another external service load balancer to assign an external IP address to the service. In the internal DNS server configuration, you should point the chosen DNS name for Astra Control Center to the load-balanced IP address.
+
NOTE: For details about the service type of "LoadBalancer" and ingress, see link:../get-started/requirements.html[Requirements].

| string
| Generic (this is the default value)

|===
====
// End snippet
+
.crds
[%collapsible]
====
|===
|Setting |Use |Description |Type |Example

| crds
| Undefined
| Your selections in this section determine how Astra Control Center should handle CRDs.
| Undefined
|

| crds.externalCertManager
| Optional
| If you use an external cert-manager, change `externalCertManager` to `true`. The default `false` causes Astra Control Center to install its own cert-manager CRDs during installation. 

CRDs are cluster-wide objects and installing them might have an impact on other parts of the cluster. You can use this flag to signal to Astra Control Center that these CRDs will be installed and managed by the cluster administrator outside of Astra Control Center.
| Boolean
| False (this value is the default)

| crds.externalTraefik
| Optional
| By default, Astra Control Center will install required Traefik CRDs. CRDs are cluster-wide objects and installing them might have an impact on other parts of the cluster. You can use this flag to signal to Astra Control Center that these CRDs will be installed and managed by the cluster administrator outside of Astra Control Center.
| Boolean
| False (this value is the default)

|===
====
// End snippet

[source]
[subs="specialcharacters,quotes"]
----
*astra_control_center.yaml*
----

[subs=+quotes]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[your_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
  volumeReclaimPolicy: "Retain"
  *ingressType: "Generic"*
  astraResourcesScaler: "Default"
  additionalValues: {}
  crds:
    externalTraefik: false
    *externalCertManager: false*
----

== Complete Astra Control Center and operator installation

. If you didn't already do so in a previous step, create the `netapp-acc` (or custom) namespace:
+
[source,console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
Sample response:
+
----
namespace/netapp-acc created
----

. Install Astra Control Center in the `netapp-acc` (or your custom) namespace:
+
[source,console]
----
kubectl apply -f astra_control_center.yaml -n [netapp-acc or custom namespace]
----
+
Sample response:
+
----
astracontrolcenter.astra.netapp.io/astra created
----

== Verify system status

You can verify system status using kubectl commands. If you prefer to use OpenShift, you can use comparable oc commands for verification steps.

.Steps

. Verify that all system components installed successfully.
+
[source,console]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
Each pod should have a status of `Running`. It may take several minutes before the system pods are deployed.
+
.Sample response
[%collapsible]
====
[subs=+quotes]
----
NAME                                       READY   STATUS    RESTARTS        AGE
acc-helm-repo-76d8d845c9-ggds2             1/1     Running   0               14m
activity-6cc67ff9f4-z48mr                  1/1     Running   2 (8m32s ago)   9m
api-token-authentication-7s67v             1/1     Running   0               8m56s
api-token-authentication-bplb4             1/1     Running   0               8m56s
api-token-authentication-p2c9z             1/1     Running   0               8m56s
asup-6cdfbc6795-md8vn                      1/1     Running   0               9m14s
authentication-9477567db-8hnc9             1/1     Running   0               7m4s
bucketservice-f4dbdfcd6-wqzkw              1/1     Running   0               8m48s
cert-manager-bb756c7c4-wm2cv               1/1     Running   0               14m
cert-manager-cainjector-c9bb86786-8wrf5    1/1     Running   0               14m
cert-manager-webhook-dd465db99-j2w4x       1/1     Running   0               14m
certificates-68dff9cdd6-kcvml              1/1     Running   2 (8m43s ago)   9m2s
certificates-68dff9cdd6-rsnsb              1/1     Running   0               9m2s
cloud-extension-69d48c956c-2s8dt           1/1     Running   3 (8m43s ago)   9m24s
cloud-insights-service-7c4f48b978-7gvlh    1/1     Running   3 (8m50s ago)   9m28s
composite-compute-7d9ff5f68-nxbhl          1/1     Running   0               8m51s
composite-volume-57b4756d64-nl66d          1/1     Running   0               9m13s
credentials-6dbc55f89f-qpzff               1/1     Running   0               11m
entitlement-67bfb6d7-gl6kp                 1/1     Running   4 (8m33s ago)   9m38s
features-856cc4dccc-mxbdb                  1/1     Running   0               9m20s
fluent-bit-ds-4rtsp                        1/1     Running   0               6m54s
fluent-bit-ds-9rqll                        1/1     Running   0               6m54s
fluent-bit-ds-w5mp7                        1/1     Running   0               6m54s
graphql-server-7c7cc49776-jz2kn            1/1     Running   0               2m29s
identity-87c59c975-9jpnf                   1/1     Running   0               9m6s
influxdb2-0                                1/1     Running   0               13m
keycloak-operator-84ff6d59d4-qcnmc         1/1     Running   0               7m1s
krakend-cbf6c7df9-mdtzv                    1/1     Running   0               2m30s
license-5b888b78bf-plj6j                   1/1     Running   0               9m32s
login-ui-846b4664dd-fz8hv                  1/1     Running   0               2m24s
loki-0                                     1/1     Running   0               13m
metrics-facade-779cc9774-n26rw             1/1     Running   0               9m18s
monitoring-operator-974db78f-pkspq         2/2     Running   0               6m58s
nats-0                                     1/1     Running   0               13m
nats-1                                     1/1     Running   0               13m
nats-2                                     1/1     Running   0               13m
nautilus-7bdc7ddc54-49tfn                  1/1     Running   0               7m50s
nautilus-7bdc7ddc54-cwc79                  1/1     Running   0               9m36s
openapi-5584ff9f46-gbrdj                   1/1     Running   0               9m17s
openapi-5584ff9f46-z9mzk                   1/1     Running   0               9m17s
packages-bfc58cc98-lpxq9                   1/1     Running   0               8m58s
polaris-consul-consul-server-0             1/1     Running   0               13m
polaris-consul-consul-server-1             1/1     Running   0               13m
polaris-consul-consul-server-2             1/1     Running   0               13m
polaris-keycloak-0                         1/1     Running   3 (6m15s ago)   6m56s
polaris-keycloak-1                         1/1     Running   0               4m22s
polaris-keycloak-2                         1/1     Running   0               3m41s
polaris-keycloak-db-0                      1/1     Running   0               6m56s
polaris-keycloak-db-1                      1/1     Running   0               4m23s
polaris-keycloak-db-2                      1/1     Running   0               3m36s
polaris-mongodb-0                          2/2     Running   0               13m
polaris-mongodb-1                          2/2     Running   0               13m
polaris-mongodb-2                          2/2     Running   0               12m
polaris-ui-5ccff47897-8rzgh                1/1     Running   0               2m33s
polaris-vault-0                            1/1     Running   0               13m
polaris-vault-1                            1/1     Running   0               13m
polaris-vault-2                            1/1     Running   0               13m
public-metrics-6cb7bfc49b-p54xm            1/1     Running   1 (8m29s ago)   9m31s
storage-backend-metrics-5c77994586-kjn48   1/1     Running   0               8m52s
storage-provider-769fdc858c-62w54          1/1     Running   0               8m54s
task-service-9ffc484c5-kx9f4               1/1     Running   3 (8m44s ago)   9m34s
telegraf-ds-bphb9                          1/1     Running   0               6m54s
telegraf-ds-rtsm2                          1/1     Running   0               6m54s
telegraf-ds-s9h5h                          1/1     Running   0               6m54s
telegraf-rs-lbpv7                          1/1     Running   0               6m54s
telemetry-service-57cfb998db-zjx78         1/1     Running   1 (8m40s ago)   9m26s
tenancy-5d5dfbcf9f-vmbxh                   1/1     Running   0               9m5s
traefik-7b87c4c474-jmgp2                   1/1     Running   0               2m24s
traefik-7b87c4c474-t9k8x                   1/1     Running   0               2m24s
trident-svc-c78f5b6bd-nwdsq                1/1     Running   0               9m22s
vault-controller-55bbc96668-c6425          1/1     Running   0               11m
vault-controller-55bbc96668-lq9n9          1/1     Running   0               11m
vault-controller-55bbc96668-rfkgg          1/1     Running   0               11m
====
// End snippet

. (Optional) To ensure the installation is completed, you can watch the `acc-operator` logs using the following command.
+
[source,console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+
NOTE: `accHost` cluster registration is one of the last operations, and if it fails it will not cause deployment to fail. In the event of a cluster registration failure indicated in the logs, you can attempt registration again through the link:../get-started/setup_overview.html#add-cluster[Add cluster workflow in the UI] or API.

. When all the pods are running, verify that the installation was successful (`READY` is `True`) and get the initial setup password you will use when you log in to Astra Control Center:
+
[source,console]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
Response:
+
----
NAME    UUID                                  VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-82  10.111.111.111  True
----
+
IMPORTANT: Copy the UUID value. The password is `ACC-` followed by the UUID value (`ACC-[UUID]` or, in this example, `ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f`).

== Set up ingress for load balancing

You can set up a Kubernetes ingress controller that manages external access to services. These procedures give setup examples for an ingress controller if you used the default of `ingressType: "Generic"` in the Astra Control Center custom resource (`astra_control_center.yaml`). You do not need to use this procedure if you specified `ingressType: "AccTraefik"` in the Astra Control Center custom resource (`astra_control_center.yaml`).

After Astra Control Center is deployed, you will need to configure the ingress controller to expose Astra Control Center with a URL.

Setup steps differ depending on the type of ingress controller you use. Astra Control Center supports many ingress controller types. These setup procedures provide example steps for the following ingress controller types:

* Istio ingress
* Nginx ingress controller
* OpenShift ingress controller

.What you'll need

* The required https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/[ingress controller] should already be deployed.
* The https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class[ingress class] corresponding to the ingress controller should already be created.

.Steps for Istio ingress

. Configure Istio ingress.
+
NOTE: This procedure assumes that Istio is deployed using the "default" configuration profile. 

. Gather or create the desired certificate and private key file for the Ingress Gateway.
+
You can use a CA-signed or self-signed certificate. The common name must be the Astra address (FQDN).
+
Sample command: 
+
[source,console]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
----

. Create a secret `tls secret name` of type `kubernetes.io/tls` for a TLS private key and certificate in the `istio-system namespace` as described in TLS secrets.
+
Sample command: 
+
[source,console]
----
kubectl create secret tls [tls secret name] --key="tls.key" --cert="tls.crt" -n istio-system
----
+
TIP: The name of the secret should match the `spec.tls.secretName` provided in `istio-ingress.yaml` file.


. Deploy an ingress resource in the `netapp-acc` (or custom-named) namespace using the v1 resource type for a schema (`istio-Ingress.yaml` is used in this example):
+
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----

. Apply the changes:
+
[source,console]
----
kubectl apply -f istio-Ingress.yaml
----

. Check the status of the ingress:
+
[source,console]
----
kubectl get ingress -n [netapp-acc or custom namespace]
----
+
Response:
+
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----

. <<Configure Astra Control Center,Finish Astra Control Center installation>>.


.Steps for Nginx ingress controller

. Create a secret of type `kubernetes.io/tls` for a TLS private key and certificate in `netapp-acc` (or custom-named) namespace as described in https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets[TLS secrets].
. Deploy an ingress resource in `netapp-acc` (or custom-named) namespace using the v1 resource type for a schema (`nginx-Ingress.yaml` is used in this example):
+
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC addess>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----

. Apply the changes:
+
[source,console]
----
kubectl apply -f nginx-Ingress.yaml
----

WARNING: NetApp recommends installing the nginx controller as a deployment rather than a daemonSet.

.Steps for OpenShift ingress controller

. Procure your certificate and get the key, certificate, and CA files ready for use by the OpenShift route.
. Create the OpenShift route:
+
[source,console]
----
oc create route edge --service=traefik --port=web -n [netapp-acc or custom namespace] --insecure-policy=Redirect --hostname=<ACC address> --cert=cert.pem --key=key.pem
----


== Log in to the Astra Control Center UI

After installing Astra Control Center, you will change the password for the default administrator and log in to the Astra Control Center UI dashboard.

.Steps
. In a browser, enter the FQDN (`https://<FQDN>`) you used in the `astraAddress` in the `astra_control_center.yaml` CR when <<Configure Astra Control Center,you installed Astra Control Center>>.
. Accept the self-signed certificates if prompted.
+
NOTE: You can create a custom certificate after login.

. At the Astra Control Center login page, enter the value you used for `email` in `astra_control_center.yaml` CR when <<Configure Astra Control Center,you installed Astra Control Center>>, followed by the initial setup password (`ACC-[UUID]`).
+
NOTE: If you enter an incorrect password three times, the admin account will be locked for 15 minutes.

. Select *Login*.
. Change the password when prompted.
+
NOTE: If this is your first login and you forget the password and no other administrative user accounts have yet been created, contact https://mysupport.netapp.com/site/[NetApp Support] for password recovery assistance.

. (Optional) Remove the existing self-signed TLS certificate and replace it with a link:../get-started/add-custom-tls-certificate.html[custom TLS certificate signed by a Certificate Authority (CA)].

== Troubleshoot the installation

If any of the services are in `Error` status, you can inspect the logs. Look for API response codes in the 400 to 500 range. Those indicate the place where a failure happened.

.Steps

. To inspect the Astra Control Center operator logs, enter the following:
+
[source,console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----

== What's next

* (Optional) Depending on your environment, complete post-installation link:configure-after-install.html[configuration steps].
* Complete the deployment by performing link:setup_overview.html[setup tasks].
