---
sidebar: sidebar
permalink: get-started/install_overview.html
keywords: Astra, Astra control center, install, deploy, download
summary: To install Astra Control Center and addressing some environment prerequisites, you'll download the bundle and install using a CLI.
---

= Install Astra Control Center overview
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

To install Astra Control Center, you'll do the following basic steps:

* <<Prepare for the Astra Control Center deployment>>
* <<Install Astra Control Center using the command-line utility>>
* <<Connect to the Astra UI>>

== Prepare for the Astra Control Center deployment
Check for any external dependencies and infrastructure needs:

. Review the link:/concepts/requirements.html[Requirements].
. Obtain a trial license from NetApp.
. Obtain permissions and instructions on how to load NetApp-supplied images into your organization's local image repository.
. Obtain the URL of the image registry where you will upload the images.
. Obtain a Kubernetes cluster that meets the Astra Control Center requirements.
. If you will use SSO, obtain SSO integration configuration details.
. Configure Trident with the ONTAP storage backend.
. Install an external load balancer on the Kubernetes cluster and set a static IP or IP range of that load balancer. The K8s cluster be configured to listen on this reachable IP address.
. Acquire an internal domain name that is routed from an internal DNS and point the domain name to the static IP or IP range using internal DNS servers, such as astra.company.com. The DNS name should point to their load-balanced IP address using their internal DNS server (or /etc/hosts for individual machines).
. Set a default storage provider in the Kubernetes cluster that is backed by a Trident storage class configured to work with ONTAP.
. Create a namespace for Astra Control Center.
+
NOTE: The Astra Control Center operator will install into a namespace called _ae-operator-system_ and the Astra application will be located in a namespace called _pcloud_. Both the Astra Control Center Operator and the Astra application will be installed into the same namespace when the product releases.

== Install Astra Control Center using the command-line utility

To install Astra Control Center, you'll download the installation bundle from the NetApp Support Site and perform a series a commands to install Astra Control Center Operator and Astra Control Center in your environment. You can use this procedure to install Astra Control Center in connected or dark site environments.

.About this task
The Astra Control Center installer does the following:

* Installs the Astra components into the `astra` namespace.
* Creates a default account.
* Creates a default administrative user called `admin` with a default one-time password of the UUID for this instance of Astra Control Center. When the installation completes, a message displays the application UUID URL and default credential. This credential is unique to each instance of Astra Control Center.
* Determines from Kubernetes that all Astra Control Center pods are running.
* Installs and connects you to the Astra UI.

.Steps
. Download the Astra Control Center bundle (`astra-control-center-21.06.9.tar.gz`) from the NetApp Support Site.
The bundle contains the following images:
+
* Astra Container
* Astra Control Center Operator

. Extract the images:
+
----
tar -xvzf astra-enterprise-21.07.xx.tar.gz
----

. Change to the Astra directory.
+
----
cd astra-control-center-21.06.9
----
. Use the following script to load ACC image to your local registry, tag the local repo image, and push to your local repo:
+
----
export REGISTRY=<URL_of_Docker_Registry>

for astraImageFile in $(ls images/*.tar) ; do
   astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')  # Load to local cache. And store the name of the loaded image trimming the 'Loaded image: '
   docker tag ${astraImage} ${REGISTRY}/${astraImage}                              # Tag with local image repo.
   docker push ${REGISTRY}/${astraImage}                                           # Push to the local repo.
done
----

. Prepare the ACC Operator to be installed by doing the following:

.. Create a namespace and secret for ACC operator. If your registry requires credentials, ensure that the credentials for the registry match.
+
----
kubectl create namespace ae-operator-system

kubectl create secret docker-registry -n ae-operator-system astra-registry-cred --docker-server=registry.localhost:5000 --docker-username=<username> --docker-password=<password>
----

.. Edit the ACC Operator deployment yaml to refer to your local registry and secret.
+
----
vim astra_enterprise_operator_deploy.yaml
----
... Change the following image references to refer to your local registry.
* `image: "registry.localhost:5000/gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"`
* `image: "registry.localhost:5000/ae-operator:0.0.11"`

... Change the image pull policy to refer to your registry's credentials. If your registry does not require secrets, comment out this entire line.
+
----
imagePullSecrets:
- name: astra-registry-cred
----

. Install the ACC Operator using the following script:
+
----
kubectl apply -f astra_enterprise_operator_deploy.yaml
----
+
Sample response:
----
namespace/ae-operator-system unchanged
customresourcedefinition.apiextensions.k8s.io/astraenterprises.astra.netapp.com configured
role.rbac.authorization.k8s.io/ae-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/ae-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/ae-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/ae-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/ae-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/ae-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/ae-operator-proxy-rolebinding unchanged
configmap/ae-operator-manager-config unchanged
service/ae-operator-controller-manager-metrics-service unchanged
deployment.apps/ae-operator-controller-manager configured
----
. Prepare to install ACC by doing the following:

.. Customize a namespace.
+
----
kubectl create namespace pcloud
----
.. Create a namespace and secret for your ACC registery. If your registry requires credentials, ensure that the imageRegistry.Name and .Secret for the registry match.
+
----
kubectl create secret docker-registry -n pcloud astra-registry-cred --docker-server=registry.localhost:5000 --docker-username=testuser --docker-password=testpassword
----
.. Edit the ACC Operator deployment yaml to refer to your local registry and secret.
+
----
vim astra_enterprise_min.yaml
----
... Change the image registry details to refer to your registry. If your registry does not require secrets, delete the entire `secret` line.
+
----
# imageRegistry:
# name: "registry.localhost:5000"
# secret: "astra-registry-cred"
----
. Install ACC:
+
----
$ kubectl apply -n pcloud -f astra_enterprise_min.yaml
----


== Helm install?

. In the command-line utility, edit the Helm values to identify the `astra` namespace.
+
----
helm install -n astra ./astra
----

. Use Helm 3 to install the Astra Control Center Operator to a Kubernetes cluster running in your data center.
+
NOTE: The Astra Helm repo must be available in your private registry.

. Load all Astra Container images into a private Docker registry running in your data center.
. Configure an Astra Control Center custom resource (CR).
. Apply the CR to your Kubernetes cluster.
. Optionally, specify the storage class to use for Astra itself (rather than the default Kubernetes storage class).
. Optionally, specify the IP and host names to use for ingress (rather than use one assigned by Kubernetes).
. Optionally, specify the initial administrative credentials (rather than getting a prompt at your initial logon).
. Optionally, specify the on-premise container registry to use (rather than the public NetApp registry).

. Verify the installation. Run `kubctl get pods -n pcloud` and look for the status of each pod to be `Running` or `Complete`.
----
$ kubectl get pods -n pcloud
NAME                                         READY   STATUS      RESTARTS   AGE
activity-6986485c96-n5ns7                    1/1     Running     0          7h12m
ae-helm-repo-866d467dbf-fsn4d                1/1     Running     0          7h13m
ae-post-deployment-8fsvs                     0/1     Completed   0          7h10m
asup-6b5d87c565-56n2l                        1/1     Running     0          7h12m
billing-55cf654d86-7ngqp                     1/1     Running     2          7h12m
cloud-extension-699bd96896-q24qt             1/1     Running     1          7h12m
composite-compute-76bfd89f46-g9kp5           1/1     Running     0          7h12m
composite-volume-6cc58f5fc7-pfr5m            1/1     Running     0          7h12m
credentials-549cd7d8f9-tvdf2                 1/1     Running     0          7h12m
entitlement-7bc45b6bd4-c7vjd                 1/1     Running     3          7h12m
features-5bc664dd6d-q98v6                    1/1     Running     0          7h12m
graphql-server-57dbb544b8-2kzvf              1/1     Running     0          7h12m
identity-76d965648-gbr85                     1/1     Running     0          7h12m
krakend-55fd947b79-cg2ct                     1/1     Running     0          7h12m
license-6bcf458478-fbfx5                     1/1     Running     0          7h12m
metrics-ingestion-service-85f5dfc595-6s5p6   1/1     Running     0          7h12m
nats-0                                       1/1     Running     0          7h13m
nats-1                                       1/1     Running     0          7h13m
nats-2                                       1/1     Running     0          7h13m
nautilus-754bcc778c-xn4nc                    1/1     Running     0          7h12m
openapi-69c6b98955-r6828                     1/1     Running     0          7h12m
polaris-mongodb-arbiter-0                    1/1     Running     0          7h13m
polaris-mongodb-primary-0                    2/2     Running     0          7h13m
polaris-mongodb-secondary-0                  2/2     Running     0          7h13m
polaris-ui-6f88ccc5fd-jdnhz                  1/1     Running     0          7h12m
polaris-vault-0                              1/1     Running     0          7h13m
storage-provider-74c59cd7c4-bqnnf            1/1     Running     0          7h12m
support-649b779cd5-7kdlb                     1/1     Running     0          7h12m
tenancy-9c46cbd87-zfcvq                      1/1     Running     0          7h12m
traefik-5f4fd4b499-7fwxg                     1/1     Running     0          7h10m
traefik-5f4fd4b499-xrgks                     1/1     Running     0          7h10m
trident-svc-77c68c8598-4xl9m                 1/1     Running     0          7h12m
----

.


. Note the one-time UUID URL and default credential that is displayed.


== Connect to the Astra UI

The Astra command-line installation tool connects you to the Astra UI.

. Using your DNS server or local `/etc/hosts` file, point `codev.astra.netapp.io` to your load-balanced IP address.
. Log into the Astra UI with the default admin credentials.
+
You will be prompted to change the default password.

. Enter a new password.

== Troubleshoot the installation

If any of the services are in Error status, you can inspect the logs with `kubectl logs -n pcloud `pod name``. Look for API response codes in the 400 to 500 range. Those indicate the place where a failure happened.

. To inspect the ACC Operator logs, enter the following:
+
----
$ kubectl logs --follow -n ae-operator-system $(kubectl get pods -n ae-operator-system -o name)  -c manager
----

== What's next

Complete the deployment by performing link:setup_overview.html[setup tasks].
