---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra Control
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra Control is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Implementations
Astra Control offers the following implementations:

* Astra Control Service: This NetApp service offering enables you to manage clusters and apps in public clouds and is run in the cloud.
* Astra Control Center: This NetApp offering enables you to manage on-premise Kubernetes and VM clusters in your data center.

== Features

Both Astra Control Service and Astra Control Center offer critical capabilities for Kubernetes application data lifecycle management:

* Create a protection policy for each of your apps
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create on-demand snapshots and backups
* Identify the health of your apps


link:/concepts/requirements.html[Learn about cluster requirements].

== Supported apps

Astra Control supports all applications running on your Kubernetes clusters.

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. Learn the difference between a link:/concepts/validated-vs-standard.html[validated app and a standard app].

No matter which type of app that you use with Astra Control, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
** For GKE clusters, Astra Control Service uses NetApp Cloud Volumes Service for Google Cloud as the backend storage for your persistent volumes.
** For AKS clusters, Astra Control Service uses Azure NetApp Files as the backend storage for your persistent volumes.
* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:
** Creates an object store in your cloud provider account, which is where backup copies are stored.
** Creates a new admin role and Kubernetes service account on the cluster.
** Uses that new admin role to install NetApp’s Trident on the cluster and to create one or more storage classes.
** Uses Trident to provision persistent volumes for your apps.
* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class.
** Learn about storage classes for GKE clusters.
** Learn about storage classes for AKS clusters.
* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra Control Service continually watches your compute for state changes, so it’s aware of any new apps that you add along the way.


== How Astra Control Center works

Astra Control Center uses several components to enable application data lifecycle management.

//The following image shows the relationship between each component:

At a high level, Astra Control Center works like this:

* You install Astra Control Center in your local environment. Astra Control Center does this:
** Discover your Kubernetes clusters.
** Discover your Trident configuration backed by the ONTAP storage backend.
+
For our first go, you'll install the images on OpenShift registry. We'll add more options later.

* You do some initial setup tasks such as these:
** Create an Astra Admin account
** Set up licensing
** Add an object store bucket that will store your app backups
** Add users and configure role-based access control (RBAC)

* You add your first Kubernetes compute to Astra Control Center. Astra Control Center then does the following:

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^].

** Uses Trident to provision persistent volumes backed by NetApp ONTAP.

** Creates one or more storage classes.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class. link:../concepts/choose-class-and-size.html[Learn about storage classes and persistent volume sizes].

* You then use Astra Control Center to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra Control Center continually watches your compute for state changes, so it's aware of any new apps that you add along the way.
