---
sidebar: sidebar
permalink: get-started/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking
summary: Get started by verifying support for your Kubernetes clusters, apps, and web browser.
---

= Astra Control Center requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Get started by verifying support for your Kubernetes clusters, apps, licenses, and web browser.

== Kubernetes cluster requirements

A Kubernetes cluster must meet the following requirements so you can discover and manage it from Astra Control Center.

=== Cluster deployment
Astra Control Center has the following cluster deployment requirements:

*Astra Control Center namespace*: You need to prepare two Kubernetes namespaces before deploying Astra Control Center:

* ae-operator-system (Used by Astra Control Center operator)
* pcloud (Used by Astra Control Center application)

*OpenShift*: If your Kubernetes cluster is managed as part of the Red Hat OpenShift Container Platform, Astra Control Center requires OpenShift 4.6 or newer.

* *Kubernetes deployment*: The Kubernetes cluster you use for Astra Control Center should already be deployed in your environment and you should have permissions to manage the cluster. This cluster should be preconfigured with the following:
** A load balancer with a static IP address or IP address range
** An internal domain name that is routed from an internal DNS server and points to the static IP address
** A default storage provider in the Kubernetes cluster that is backed by a Trident storage class to work with ONTAP.

* *Kubernetes version*: A cluster must be running Kubernetes version 1.17 or later.

* *Image type*: The image type for each worker node must be Ubuntu.

* *Image registry*: You must have an existing private Docker image registry to which you can push Astra Control Center build images. You must have tagged the images for the private container registry.

* *Cluster state*: Clusters must be running in a healthy state and have at least one online worker node.

* *Private clusters* If the cluster is private, it must have the https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[master authorized network^] set to allow the Astra IP addresses:
** 54.164.233.140/32
** 3.218.120.204/32
** 34.193.99.138/32

* *Compute and memory requirements*:

* *Trident / ONTAP storage configuration*: Astra Control Center requires that Trident version 21.01 or newer already be installed and configured to work with NetApp ONTAP version 9.5 or newer as the storage backend.

=== Supported apps

Astra Control Center supports all applications running on your Kubernetes clusters. See link:../release-notes/known-limitations.html[Known limitations].

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. link:../learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app].

No matter which type of app that you use with Astra Control Center, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

=== App management requirements
Astra Control Center has the following app management requirements:

* *Licensing*: You need an Astra Control Center license to deploy and manage apps using Astra Control Center.
* *Helm*: If you use Helm to deploy apps, Astra Control Center requires Helm version 3. Managing and cloning apps deployed with Helm 3 (or upgraded from Helm 2 to Helm 3) are fully supported.

== Access to the internet

You should determine whether you have outside access to the internet. If you do not, some functionality might be limited, such as monitoring data from NetApp Cloud Insights, Support data, or Licensing information.

If you do have access to the internet, decide which of the following NetApp systems you will authorize Astra Control Center to integrate with:

* Cloud Insights for monitoring and metrics
* Active IQ and SmartSolve for supportability
* IPA for license automation

== License

Astra Control Center requires an Astra Control Center license for full functionality.

If you want to try Astra Control Center, you can use a 90-day evaluation license.

== Load balancing

Astra Control Center requires the Kubernetes cluster to have a load balancer installed and configured with an accessible external IP address. In the internal DNS server configuration, you should point the chosen DNS name for Astra Control Center to the load-balanced IP address.

== Networking requirements

Astra Control Center communicates using the following TCP ports. You should ensure that these ingress ports are allowed through any firewalls, and configure firewalls to allow any HTTPS egress traffic originating from the Astra network:

|===
|Product |Port |Protocol |Direction |Purpose

.13+|Astra Control Center
|443
|HTTPS
|Ingress
|UI / API access

|9090
|HTTPS
|Ingress
|Metrics data to Metrics consumer (Prometheus)

|n/a
|HTTPS
|Ingress
|Data to Cloud Insights

|n/a
|HTTPS
|Egress
|Log processing data to logs consumer

|n/a
|HTTPS
|Egress
|NetApp AutoSupport messages to NetApp Active IQ

|n/a
|HTTPS
|Egress
|Bucket service communication with bucket provider

|n/a
|HTTPS
|Egress
|Metrics flow from ONTAP

|n/a
|HTTPS
|Egress
|Storage Backend service communication with ONTAP

|n/a
|HTTPS
|Egress
|Cloud extension communication with managed cluster

|n/a
|HTTPS
|Egress
|Nautilus communication with managed cluster

|n/a
|HTTPS
|Egress
|Trident service communication with managed cluster’s Trident

.2+|Trident
|34571
|HTTPS
|Ingress
|Node pod communication

|9220
|HTTPS
|Ingress
|Metrics endpoint
|===

== Supported web browsers

Astra Control Center supports recent versions of Firefox, Safari, and Chrome with a minimum resolution of 1280 x 720.

== Integration with your organization

Before you deploy Astra Control Center, you should determine which internal integrations should occur, including the following:

* Single sign on
* SMTP server for email notifications

If you want to integrate these options, you should obtain the following:

* SSO integration confirmation details
* SMTP server configuration details
