---
sidebar: sidebar
permalink: get-started/setup_overview.html
keywords: set up, setup, Astra Control Center, add license, add cluster, import storage, add bucket
summary: After you install Astra Control Center, log in to the UI, and change your password, you'll want to set up licenses, add clusters, important storage, and add buckets.
---

= Set up Astra Control Center
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

After you install Astra Control Center, log in to the UI, and change your password, you'll want to set up licenses, add clusters, important storage, and add buckets.

.Options
* <<Add a license for Astra Control Center>>
* <<Add cluster>>
* <<Import a storage backend>>
* <<Add a bucket>>

== Add a license for Astra Control Center
You can add a new license using the UI or API to gain full Astra Control Center functionality. Without a license, your usage of Astra Control Center is limited to managing users and adding new clusters.

.Before you begin
When you downloaded Astra Control Center from the  https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab[NetApp Support Site], you also downloaded the NetApp license file (NLF). Ensure you have access to this license file.

.Options
* <<Add an evaluation license>>
+
NOTE: To update an existing evaluation or full license, see link:../use/update-license.html[Update an existing license].

* <<Add a full license>>

=== Add an evaluation license
You can try Astra Control Center with an evaluation license, which lets you use Astra Control Center for 90 days from the date you downloaded Astra Control Center. You need to work with your NetApp sales contact to obtain an evaluation license, which is associated with your NetApp Support account.

.Steps
. Log in to the Astra Control Center UI.
. From the left navigation, select *Account* > *Licenses*.
. Select the *Add License* dropdown menu, and choose *Connect to NetApp Support*.
. Enter your NetApp Support site credentials, and select *Connect*.

The *Account* > *Licenses* page displays the license information, expiration date, license serial number, cluster ID, and CPU units used.

=== Add a full license

Astra Control Center licenses measure CPU resources using Kubernetes CPU units. The CPU cores that Astra Control Center is deployed on are not counted against the CPU units consumed in the license. Before adding a license, you need to obtain the license file (NLF) that you downloaded with the Astra Control Center installation bundle from the https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab[NetApp Support Site].

NOTE:  If your installation grows to exceed the licensed number of CPU units, Astra Control Center prevents you from managing new applications. An alert is displayed when capacity is exceeded.

.Steps
. Log in to the Astra Control Center UI.
. From the Dashboard, select *Manage Licenses*.
+
Alternatively, from the left navigation, select *Account* > *Licenses*.

. Select *Add a license*.
. Browse to the license file (NLF) that you downloaded.
. Select *Add License*.

The *Account* > *Licenses* page displays the license information, expiration date (for evaluation licenses), license serial number, cluster ID, and CPU units used.

Full Astra Control Center functionality is now enabled.

== Add cluster

. From the Astra UI, select *Clouds*.
. Select the cloud to which you want to add the cluster.
. Select *Add Cluster*.
. Enter the following:
+
* Name of the cluster
* Cluster credentials

== Import a storage backend

Add storage for your on-premises Kubernetes applications. Astra Control discovers and uses the already-deployed resources, including Trident, ONTAP, and associated storage classes. Managing storage clusters in Astra Control as a storage backend enables you to get linkages between persistent volumes (PVs) and the storage backend.

Admins can import an already discovered storage backend using these options:

* <<Import storage backend using Dashboard>>
* <<Import storage backend using Backends option>>

=== Import storage backend using Dashboard
. From the Dashboard do one of the following:
** From the Dashboard Getting started section, select *Add storage backend*.
** From the Dashboard *Resource Summary > Storage backends* section, select *Add*.
. Enter the ONTAP admin credentials and select *Review information*.
. Confirm the backend details and select *Import storage backend*.
+
The imported backend appears in the list with summary information.

=== Import storage backend using Backends option
. In the left navigation area, select *Backends*.
. Select *Import existing storage backend*.
. Enter the ONTAP admin credentials and select *Review information*.
. Confirm the backend details and select *Import storage backend*.
+
The imported backend appears in the list with summary information.
. To see details of the backend storage, select it.
+
TIP: Persistent volumes used by apps in the managed compute cluster are also displayed.

== Add a bucket

Adding object store bucket providers is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters. Using Astra Control, add an object store provider as your backup destination.

NOTE: You can also add a bucket to Astra Control Center using the API. See the API documentation for more details.

You don’t need a bucket if you are:

* Cloning your application configuration and persistent storage to the same cluster
* Cloning to a different cluster using an existing backup or snapshot

Use any of the following bucket types:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Generic S3

Admins can add object store buckets. When you use Astra Control to back up or clone your application data, Astra Control stores those backups or clones in the object store buckets that you define here.

When you add a bucket, Astra Control marks one bucket as the default bucket indicator. The first bucket that you create becomes the default bucket.

.Steps

. In the left navigation area, select Buckets.
.. Select Add.
.. Select the bucket type.
.. Enter the existing bucket name and optional description.
+
TIP: The bucket name and description appear as a backup location that you can choose later when you’re creating a backup. The name also appears during protection policy configuration.

.. Enter the or IP address of the S3 server.
.. If you want this bucket to be the default bucket for all backups, check the `Make this bucket the default bucket for this private cloud` option.
+
NOTE: This option does not appear for the first bucket you create.

.. Continue by adding <<Add S3 access credentials,credential information>>.

=== Add S3 access credentials

Add S3 access credentials at any time.

.Steps

. From the Buckets dialog, select either the *Add* or *Use existing* tab.
.. Enter a name for the credential that distinguishes it from other credentials in Astra Control.
.. Enter the access ID and secret key either by uploading the file or by pasting the contents from your clipboard.

== What's next?

Now that you’ve logged in and added compute to Astra Control Center, you're ready to start using Astra Control Center's application data management features.

* link:../use/manage-users.html[Manage users]
* link:../use/manage-apps.html[Start managing apps]
* link:../use/protect-apps.html[Protect apps]
* link:../use/clone-apps.html[Clone apps]
* link:../use/manage-notifications.html[Manage notifications]
* link:../use/manage-notifications.html[???Connecting to Cloud Insights???]

[discrete]
== Find more information
* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra API]
