---
sidebar: sidebar
permalink: get-started/videos.html
keywords: videos, Astra videos
summary: Many of the pages on this doc site include videos that show how to complete a task using Astra. If you're just interested in videos, we've made it easier for you by collecting all of the videos on this single page (kind of like a playlist).
---

= Astra videos
:hardbreaks:
:icons: font
:imagesdir: ../media/

Many of the pages on this doc site include videos that show you how to complete a task for Astra. If you're just interested in videos, we've made it easy for you by collecting all of the videos on this single page (kind of like a playlist).

== Videos for setting up Astra Enterprise

The following videos show how to complete set up requirements before you can discover Kubernetes clusters running on-premise.

=== Enable APIs

Your project needs permissions to access specific Astra APIs. The following video shows how to enable the APIs. link:set-up-google-cloud.html#enable-apis-in-your-project[Learn more about enabling APIs].

video::get-started/video-enable-gcp-apis.mp4[width=848, height=480]


== Videos for using Astra Enterprise

The following videos show how to complete common tasks using Astra Enterprise.

=== Manage compute from Astra Enterprise

After you log in to Astra, your first step is to add Kubernetes compute. link:add-first-cluster.html[Learn more about managing compute].

video::get-started/video-manage-cluster.mp4[width=848, height=480]

=== Configure a protection policy

A protection policy protects an app by creating snapshots, backups, or both at a defined schedule. You can choose to create snapshots and backups hourly, daily, weekly, and monthly, and you can specify the number of copies to retain. link:../use/protect-apps.html[Learn more about configuring protection policies].

video::use/video-set-protection-policy.mp4[width=848, height=480]
