---
sidebar: sidebar
permalink: overview/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra
:hardbreaks:
:icons: font
:imagesdir: ../media/overview/

Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Implementations
Astra offers the following implementations:

* Astra Service: This NetApp service offering is run in the cloud and enables you to manage clusters and apps in public clouds.
* Astra Enterprise: This offering operates on your Kubernetes clusters in your on-premise data center and enables you to manage on-premise Kubernetes clusters and VM clusters.

== Features

Both Astra Service and Astra Enterprise offer critical capabilities for Kubernetes application data lifecycle management:

* Create a protection policy for each of your apps
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create on-demand snapshots and backups
* Identify the health of your apps


link:../concepts/requirements.html[Learn about cluster requirements].

== How Astra Enterprise works

Astra Enterprise uses several components to enable application data lifecycle management.

//The following image shows the relationship between each component:

At a high level, Astra Enterprise works like this:

* You install Astra Enterprise in your local environment and let Astra Enterprise do this:
** Discover your Kubernetes clusters.
** Discover your Trident configuration backed by the ONTAP storage backend.
+
For our first go, you'll install the images on OpenShift registry. We'll add more options later.

* You do some initial setup tasks such as these:
** Create an Astra Admin account
** Set up licensing
** Add an object store bucket that will store your app backups
** Add users and configure role-based access control (RBAC)

* You add your first Kubernetes compute to Astra. Astra then does the following:

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^].

** Uses Trident to provision persistent volumes backed by NetApp ONTAP.

** Creates one or more storage classes.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class. link:../learn/choose-class-and-size.html[Learn about storage classes and persistent volume sizes].

* You then use Astra to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

* You can monitor capacity and IOPS for your Kubernetes clusters using Cloud Insights, a NetApp cloud infrastructure monitoring tool that is offered as a service.
