---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: astra, control center, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues with this release
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

== Reusing buckets impacted by
// ASTRACTL-9296 (Low probability)
If you try to reuse a bucket after changing Astra Control Center installation configuration, backup and restore will fail. You must use a different bucket or completely clean out the previously used bucket.

== App with user-defined label goes into "removed" state
// ASTRACTL-9643
If you define an app with a non-existent k8s label, Astra Control Center will create, manage, and then immediately remove the app. To avoid this, add the k8s label to pods and resources after the app is managed by Astra Control Center???



== Clone performance impacted by large persistent volumes

Clones of very large and consumed persistent volumes might be intermittently slow, dependent on cluster access to the object store. If the clone is hung and no data has been copied for more than 30 minutes, Astra Enterprise terminates the clone action.
