---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: astra, control center, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:source-highlighter: highlight.js
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

The following known issues affect the current release:

.Apps
* <<Restore of an app results in PV size larger than original PV>>
* <<App clones fail using a specific version of PostgreSQL>>
* <<App clones fail when using Service Account level OCP Security Context Constraints (SCC)>>
* <<App clones fail after an application is deployed with a set storage class>>
* <<App backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed>>
<<Adding another app to replicated source namespace keeps app replicating indefinitely>>

.Clusters
* <<Managing a cluster with Astra Control Center fails when default kubeconfig file contains more than one context>>

.Other issues
* <<App data management operations fail with Internal Service Error (500) when Astra Trident is offline>>
* <<Snapshots might fail with snapshot controller version 4.2.0>>
* <<Event logs are not showing up in Clouds Insights due to incorrect DNS setting>>

== Restore of an app results in PV size larger than original PV
//DOC-3562/ASTRACTL-9560/Q2 and PI4/PI5
If you resize a persistent volume after creating a backup and then restore from that backup, the persistent volume size will match the new size of the PV instead of using the size of the backup.

== App clones fail using a specific version of PostgreSQL
//DOC-3543/ASTRACTL-9408/Q2 and PI4/PI5
App clones within the same cluster consistently fail with the Bitnami PostgreSQL 11.5.0 chart. To clone successfully, use an earlier or later version of the chart.

== App clones fail when using Service Account level OCP Security Context Constraints (SCC)
//ASTRACTL-10060/DOC-3594/Q2 and PI4/PI5
An application clone might fail if the original security context constraints are configured at the service account level within the namespace on the OpenShift Container Platform cluster. When the application clone fails, it appears in the Managed Applications area in Astra Control Center with status `Removed`. See the https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center[knowledgebase article] for more information.

== App backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed
DOC-4419/ASTRACTL-19849
Backups and snapshots fail with a `UI 500 error` in this scenario. As a workaround, do one of the following:

* Refresh the app list.
* Unmanage an app and then define and manage it again with Astra Control.
* Define and manage a new app. This has the effect of restoring replication operations on all apps for that cluster.

== Adding another app to a replicated source namespace keeps the app replicating indefinitely
DOC-4424/ASTRACTL-20017
Do not add PVCs to an Astra managed app if the app is part of an existing replication relationship. Doing so causes the replication status of `replicating` to hang. If you encounter this error, delete the app replication relationship, add the PVCs, and then create the replication relationship again.

== App clones fail after an application is deployed with a set storage class
//DOC-3892/ASTRACTL-13183/PI4/PI5
After an application is deployed with a storage class explicitly set (for example, `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`), subsequent attempts to clone the application require that the target cluster have the originally specified storage class.
Cloning an application with an explicitly set storage class to a cluster that does not have the same storage class will fail. There are no recovery steps in this scenario.

== Managing a cluster with Astra Control Center fails when default kubeconfig file contains more than one context
//ASTRACTL-8872/DOC-3612/Q2 and PI4/PI5
You cannot use a kubeconfig with more than one cluster and context in it. See the link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context[knowledgebase article] for more information.

== App data management operations fail with Internal Service Error (500) when Astra Trident is offline
//DOC-3903/ASTRA-13162/PI4/PI5
If Astra Trident on an app cluster goes offline (and is brought back online) and 500 internal service errors are encountered when attempting app data management, restart all of the Kubernetes nodes in the app cluster to restore functionality.

== Snapshots might fail with snapshot controller version 4.2.0
//DOC-3891 and ASTRACTL-12523/PI5
When you use Kubernetes snapshot-controller (also known as external-snapshotter) version 4.2.0 with Kubernetes 1.20 or 1.21, snapshots can eventually begin to fail. To prevent this, use a different https://kubernetes-csi.github.io/docs/snapshot-controller.html[supported version^] of external-snapshotter, such as version 4.2.1, with Kubernetes versions 1.20 or 1.21.

. Run a POST call to add an updated kubeconfig file to the `/credentials` endpoint and retrieve the assigned `id` from the response body.

. Run a PUT call from the `/clusters` endpoint using the appropriate cluster ID and set the `credentialID` to the `id` value from the previous step.

After you complete these steps, the credential associated with the cluster is updated and the cluster should reconnect and update its state to `available`.

== Event logs are not showing up in Cloud Insights due to incorrect DNS setting
DOC-4405/ASTRACTL-16703
The default DNS mode for Fluent Bit for a managed cluster in Astra Control is UDP. If there are DNS resolution failures while using FQDN that appear in fluent-bit pod logs on the managed cluster, change the telemetry-service environment variable `TELEMETRY_FLUENTBIT_DNS_MODE` from UDP to TCP. This change ensures the managed cluster takes TCP as the DNS mode and the resolves resolution errors.

== Find more information

* link:../release-notes/known-issues-ads.html[Known issues with Astra Data Store prreview and this Astra Control Center release]
* link:../release-notes/known-limitations.html[Known limitations]
