---
sidebar: sidebar
permalink: release-notes/known-issues-ads.html
keywords: astra, control center, ads, data store, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues with Astra Data Store and this Astra Control Center release
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

The following known issues affect the management of Astra Data Store with this current release of the Astra Control Center:

== Astra Data Store backend cannot be added to Astra Control Center management due to MongoDB pod failure
//ASTRACTL-13036/DOC-3904/BURT1439334
When you attempt to add Astra Data Store as a default backend for an Astra Control Center deployment, the Astra Data Store persistent volumes are not mounted on the Astra Control Center cluster, the MongoDB pod liveness probe fails, and the backend fails to be added to management.

To correct this issue, do the following:

. Edit the Astra Control Center custom resource (CR) file (astra_control_center_min.yaml) and include the following under `spec:`:
+
----
additionalValues:
    polaris-mongodb:
      mongodb:
        livenessProbe:
          initialDelaySeconds: 400
      metrics:
        livenessProbe:
          initialDelaySeconds: 400
----

. Apply updates to astra_control_center_operator_deploy.yaml:
+
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----

. Change the Helm install timeout:
+
----
kubectl set env -n netapp-acc-operator deployment/acc-operator-controller-manager ACCOP_HELM_INSTALLTIMEOUT=15m
----

. Apply the updates to astra_control_center_min.yaml:
+
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom namespace]
----

== Astra Control Center shows Astra Data Store backend in `Unknown` state
//DOC-3916/ASTRACTL-13196/ASTRACTL-13134
Astra Control Center shows the Astra Data Store storage backend in an `Unknown` state from the Backends page in the UI. In this condition, the backend is actually available and can be communicated with. A component within the backend is likely in an unhealthy state and needs to be returned to a healthy state for the backend to show as `available`.

== Find more information
//Add ADS links
* link:../release-notes/known-limitations.html[Known limitations for this release]
