---
sidebar: sidebar
permalink: release-notes/known-limitations.html
keywords: astra, control center, limitations, known limitations, interoperability
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== The same cluster cannot be managed by two Astra Control Center instances
/DOC-3600/Q2/PI4/PI5
If you want to manage a cluster on another Astra Control Center instance, you should first link:../use/unmanage.html#stop-managing-compute[unmanage the cluster] from the instance on which it is managed before you manage it on another instance. After you remove the cluster from management, verify that the cluster is unmanaged by executing this command:

----
oc get pods n -netapp-monitoring
----

There should be no pods running in that namespace or the namespace should not exist. If either of those are true, the cluster is unmanaged.

== Astra Control Center cannot manage two identically named clusters
/DOC-3744/ASTRACTL-11632/PI5
If you try to add a cluster with the same name of a cluster that already exists, the operation will fail. This issue most often occurs in a standard Kubernetes environment if you have not changed the cluster name default in Kubernetes configuration files.

As a workaround, do the following:

. Edit your kubeadm-config ConfigMap:
+
----
kubectl edit configmaps -n kube-system kubeadm-config
----

. Change the `clusterName` field value from `kubernetes` (the Kubernetes default name) to a unique custom name.
. Edit kubeconfig (`.kube/config`).
. Update cluster name from `kubernetes` to a unique custom name (`xyz-cluster` is used in the examples below). Make the update in both `clusters` and `contexts` sections as shown in this example:
+
[subs=+quotes]
----
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ExAmPLERb2tCcjZ5K3E2Njk4eQotLExAMpLEORCBDRVJUSUZJQ0FURS0txxxxXX==
    server: https://x.x.x.x:6443
  *name: xyz-cluster*
contexts:
- context:
    *cluster: xyz-cluster*
    namespace: default
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
----

== Clones of apps installed using pass by reference operators can fail
//PI5
Astra Control supports apps installed with namespace-scoped operators. These operators are generally designed with a "pass-by-value" rather than "pass-by-reference" architecture. The following are some operator apps that follow these patterns:

* https://github.com/k8ssandra/cass-operator/tree/v1.7.1[Apache K8ssandra^]
+
NOTE: For k8ssandra, in-place restore operations are supported. A restore operation to a new namespace or cluster requires that the original instance of the application to be taken down. This is to ensure that the peer group information carried over does not lead to cross-instance communication. Cloning of the app is not supported.

* https://github.com/jenkinsci/kubernetes-operator[Jenkins CI^]
* https://github.com/percona/percona-xtradb-cluster-operator[Percona XtraDB Cluster^]

Note that Astra Control might not be able to clone an operator that is designed with a “pass-by-reference” architecture (for example, the CockroachDB operator). During these types of cloning operations, the cloned operator attempts to reference Kubernetes secrets from the source operator despite having its own new secret as part of the cloning process. The clone operation might fail because Astra Control is unaware of the Kubernetes secrets in the source operator.

== In-place restore operations of apps that use a certificate manager are not supported
/ASTRACTL-16478/DOC-4152/PI5
This release of Astra Control Center does not support in-place restore of apps with certificate managers. Restore operations to a different namespace and clone operations are supported.

== OLM-enabled and cluster-scoped operator deployed apps not supported
/DOC-3553/ASTRACTL-9490/AD AH/Q2/PI4/PI5
Astra Control Center does not support application management activities with cluster-scoped operators.

== Cloning apps can only be done with same K8s distribution
/ASTRACTL-7079
If you clone an app between clusters, the source and destination clusters must be the same distribution of Kubernetes. For example, if you clone an app from an OpenShift 4.7 cluster, use a destination cluster that is also OpenShift 4.7.

== S3 buckets in Astra Control Center do not report available capacity
/DOC-3561/ASTRACTL-9425/Q2 and PI4
Before backing up or cloning apps managed by Astra Control Center, check bucket information in the ONTAP or StorageGRID management system.

== Apps deployed with Helm 2 are not supported
/From requirements section
If you use Helm to deploy apps, Astra Control Center requires Helm version 3. Managing and cloning apps deployed with Helm 3 (or upgraded from Helm 2 to Helm 3) is fully supported. For more information, see link:../get-started/requirements.html[Astra Control Center requirements].

== Astra Control Center does not validate the details you enter for your proxy server
/From email request/AD AH/Q2 and PI4
Ensure that you link:../use/monitor-protect.html#add-a-proxy-server[enter the correct values] when establishing a connection.

== Data protection for Astra Control Center as app not yet available
/DOC-3583/Q2 and PI4
This release does not support the ability to manage Astra as an app using snapshot, backup, or restore options.

== Existing connections to a Postgres pod causes failures
/From ACS RN
When you perform operations on Postgres pods, you shouldn't connect directly within the pod to use the psql command. Astra Control requires psql access to freeze and thaw the databases. If there is a pre-existing connection, the snapshot, backup, or clone will fail.

== Find more information

* link:../release-notes/known-issues.html[Known issues]
* link:../release-notes/known-issues-ads.html[Known issues with Astra Data Store preview and this Astra Control Center release]
