---
sidebar: sidebar
permalink: release-notes/resolved-issues.html
keywords: astra, control center, fixed bugs, fixes, resolved issues
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Resolved issues
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

These issues have been corrected in this release of the product.

== Selecting a bucket provider type with credentials for another type causes data protection failures
//DOC-3560/ASTRACTL-9574/ASTRACTL-9504/Q2 and PI4
When you add a bucket, select the correct bucket provider and enter the right credentials for that provider. For example, the UI accepts NetApp ONTAP S3 as the type and accepts StorageGRID credentials; however, this will cause all future app backups and restores using this bucket to fail.

== Custom app execution hook scripts time out and cause post-snapshot scripts not to execute
//ASTRACTL-12927/DOC-3909
If an execution hook takes longer than 25 minutes to run, the hook will fail, creating an event log entry with a return code of "N/A". Any affected snapshot will timeout and be marked as failed, with a resulting event log entry noting the timeout.

Because execution hooks often reduce or completely disable the functionality of the application they are running against, you should always try to minimize the time your custom execution hooks take to run.

== Simultaneous app restore operations in the same namespace can fail
//DOC-3910 and ASTRACTL-13362
If you try to restore one or more individually managed apps within a namespace simultaneously, the restore operations can fail after a long period of time. As a workaround, restore each app one at a time.

== Upgrade fails if source version uses a container image registry that does not require authentication and target version uses a container image registry that requires authentication
//DOC-3919 and ASTRACTL-13466
If you upgrade an Astra Control Center system that uses a registry that doesn't require authentication to a newer version that uses a registry that requires authentication, the upgrade fails. As a workaround, perform the following steps:

. Log in to a host that has network access to the Astra Control Center cluster.
. Ensure that the host has the following configuration:
+
* `kubectl` version 1.19 or later is installed
* The KUBECONFIG environment variable is set to the kubeconfig file for the Astra Control Center cluster

. Execute the following script:
+
[source,shell]
----

namespace="<netapp-acc>"
statefulsets=("polaris-vault" "polaris-mongodb" "influxdb2" "nats" "loki")
for ss in ${statefulsets[@]}; do
	existing=$(kubectl get -n ${namespace} statefulsets.apps ${ss} -o jsonpath='{.spec.template.spec.imagePullSecrets}')
	if [ "${existing}" = "[{}]" ] || [ "${existing}" = "[{},{},{}]" ]; then
		kubectl patch -n ${namespace} statefulsets.apps ${ss} --type merge --patch '{"spec": {"template": {"spec": {"imagePullSecrets": []}}}}'
	else
		echo "${ss} not patched"
	fi
done
----
+
You should see output similar to the following:
+
----
statefulset.apps/polaris-vault patched
statefulset.apps/polaris-mongodb patched
statefulset.apps/influxdb2 patched
statefulset.apps/nats patched
statefulset.apps/loki patched
----
. Proceed with the upgrade using the link:../use/upgrade-acc.html#add-the-images-to-your-local-registry[Astra Control Center upgrade instructions].

== Find more information

* link:../release-notes/known-issues.html[Known issues]
* link:../release-notes/known-limitations.html[Known limitations]
* link:../release-notes/known-issues-ads.html[Known issues with Astra Data Store preview and this Astra Control Center release]
